/**
 * Future Age puppets (DESIGN A5.6 units and turrets, A11 art direction, the Spire base).
 * Each entry is a procedural visual source keyed like its manifest id.
 */
import { AGE_ZONES } from '../palette';
import '../parts/future';
import { sized } from '../parts/registry';
import { base, type BasePuppet } from '../rigs/base';
import { biped } from '../rigs/biped';
import { slot } from '../rigs/common';
import { flyer, vehicle, walker } from '../rigs/machines';
import { turret, type TurretPuppet } from '../rigs/turret';
import type { BoneDef, PuppetDef, SlotDef } from '../types';

const Z = AGE_ZONES.future;
const zone = (k: string): number => Z[k] ?? 0x888888;

/** Extra future zones. Magenta and mint are outside the team hue bands; cyan stays an accent. */
const X = {
  ...Z,
  glass: 0xbfe8e0,
  clockface: 0xf4f6f8,
  void: 0x5a3f7a,
  void2: 0x3e2a58,
  lilac: 0xc9b8f0,
  crystal: 0xd8c8f0,
  smoke: 0x8a8d96,
};

const white = zone('cloth2');
const charcoal = zone('cloth');
/** Armoured troops: white plates on the arms and shins over a charcoal suit. */
const armored = { ...X, sleeve: white, forearm: white, glove: zone('metal2'), pants: charcoal, shin: white, boot: zone('metal2') };

function scaleBones(bones: BoneDef[], k: number): BoneDef[] {
  return bones.map((b) => ({ ...b, x: b.x * k, y: b.y * k }));
}
function scaleSlots(slots: SlotDef[], k: number): SlotDef[] {
  return slots.map((s) => ({ ...s, part: sized(s.part, k), x: (s.x ?? 0) * k, y: (s.y ?? 0) * k }));
}

const MECH_K = 1.16;
const TITAN_K = 1.06;
/** W7 Future wave fallback scales (the Blender sheets are the shipped art). */
const CRAB_K = 1.1;
const CARRIER_K = 1.6;
const ANDROID = { ...armored, skin: zone('metal2'), glove: zone('metal2') };

export const FUTURE_UNITS: PuppetDef[] = [
  biped({
    id: 'unit.photon_knight',
    age: 'future',
    palette: armored,
    head: 'future.head.plain',
    eyes: null,
    hat: [{ part: 'future.helmet.knight', tag: 'prop' }],
    torso: 'future.torso.armor',
    pelvis: 'future.pelvis.armor',
    weapon: { part: 'future.photonblade', rot: 100 },
    extras: [slot('future.skirt', 'pelvis', 21)],
    pose: { armF: -30, foreF: -50, armB: 10, foreB: -30 },
    attack: 'biped.attack.swing',
    group: 'infantry',
    size: 'small',
  }),
  biped({
    id: 'unit.pulse_trooper',
    age: 'future',
    palette: armored,
    head: 'future.head.plain',
    eyes: null,
    hat: [{ part: 'future.helmet.trooper', tag: 'prop' }],
    torso: 'future.torso.armor',
    pelvis: 'future.pelvis.armor',
    weapon: { part: 'future.plasmarifle', rot: 180, y: 2, muzzle: { x: 0, y: -38 } },
    pose: { armF: -78, foreF: -12, armB: -64, foreB: -46 },
    attack: 'biped.attack.shoot',
    group: 'ranged',
    size: 'small',
    twirl: false,
  }),
  walker({
    id: 'unit.walker_mech',
    age: 'future',
    palette: { ...X, skin: 0xcfa98c },
    height: 106,
    center: 50 * MECH_K,
    bones: scaleBones(
      [
        { id: 'hull', parent: 'spin', x: 0, y: 0 },
        { id: 'pilot', parent: 'hull', x: 10, y: -22 },
        { id: 'legB', parent: 'hull', x: -6, y: 6 },
        { id: 'shinB', parent: 'legB', x: 0, y: 20 },
        { id: 'footB', parent: 'shinB', x: 0, y: 20 },
        { id: 'legF', parent: 'hull', x: 6, y: 6 },
        { id: 'shinF', parent: 'legF', x: 0, y: 20 },
        { id: 'footF', parent: 'shinF', x: 0, y: 20 },
        { id: 'armB', parent: 'hull', x: -16, y: -22, rot: 12 },
        { id: 'foreB', parent: 'armB', x: 0, y: 16, rot: -30 },
        { id: 'armF', parent: 'hull', x: 18, y: -20, rot: -26 },
        { id: 'foreF', parent: 'armF', x: 0, y: 16, rot: -44 },
      ],
      MECH_K,
    ),
    slots: scaleSlots(
      [
        slot('future.mech.upperarm', 'armB', 3, { tone: 'back', noWidth: true }),
        slot('future.mech.forearm', 'foreB', 4, { tone: 'back', noWidth: true }),
        slot('future.mech.thigh', 'legB', 5, { tone: 'back' }),
        slot('future.mech.shin', 'shinB', 6, { tone: 'back' }),
        slot('future.mech.foot', 'footB', 7, { tone: 'back' }),
        slot('future.mech.pilot', 'pilot', 9, { tag: 'prop' }),
        // A11 redundant team cue: a pennant on every heavy
        slot('future.turret.flag', 'hull', 9.5, { x: -16, y: -20, id: 'pennant', noWidth: true }),
        slot('future.mech.hull', 'hull', 10),
        slot('future.mech.thigh', 'legF', 12, { id: 'thighF' }),
        slot('future.mech.shin', 'shinF', 13, { id: 'shinFs' }),
        slot('future.mech.foot', 'footF', 14, { id: 'footFs' }),
        slot('future.mech.upperarm', 'armF', 15, { id: 'upperF', noWidth: true }),
        slot('future.mech.claw', 'foreF', 16, { tag: 'weapon', noWidth: true }),
      ],
      MECH_K,
    ),
    attack: 'walker.attack.punch',
    group: 'heavy',
    size: 'large',
    legLen: 40 * MECH_K,
    legDeg: 20,
    speed: 50,
  }),
  biped({
    id: 'unit.rail_gunner',
    age: 'future',
    height: 70,
    palette: { ...armored, skin: 0xa8876f },
    head: 'future.head.grin',
    eyes: 'shared.eyes.angry',
    hat: [{ part: 'future.helmet.rail', tag: 'prop' }],
    torso: 'future.torso.armor',
    back: [{ part: 'future.capacitor', x: -10, y: -10 }],
    pelvis: 'future.pelvis.armor',
    weapon: { part: 'future.railgun', rot: 180, y: 3, muzzle: { x: 0, y: -56 } },
    pose: { armF: -78, foreF: -12, armB: -64, foreB: -46 },
    attack: 'biped.attack.heavyShot',
    group: 'antiArmor',
    size: 'medium',
    twirl: false,
  }),
  flyer({
    id: 'unit.repair_drone',
    age: 'future',
    palette: X,
    height: 38,
    center: 17,
    bones: [
      { id: 'body', parent: 'spin', x: 0, y: 0 },
      { id: 'rotor', parent: 'body', x: -13, y: -12 },
      { id: 'rotorB', parent: 'body', x: 13, y: -12 },
      { id: 'emitter', parent: 'body', x: 0, y: 10 },
      { id: 'muzzle', parent: 'emitter', x: 0, y: 5 },
    ],
    slots: [
      slot('future.drone.pod', 'body', 8, { x: -13, y: -12, noWidth: true }),
      slot('future.drone.pod', 'body', 8, { x: 13, y: -12, id: 'podB', noWidth: true }),
      slot('future.drone.emitter', 'emitter', 9),
      slot('future.drone.body', 'body', 10),
      slot('future.drone.blade', 'rotor', 11, { y: -3, noWidth: true }),
      slot('future.drone.blade', 'rotorB', 11, { y: -3, id: 'bladeB', noWidth: true }),
    ],
    muzzleBone: 'muzzle',
    attack: 'flyer.attack.beam',
    ability: 'ability.repair_beam',
    group: 'support',
    size: 'small',
    speed: 70,
  }),
  biped({
    id: 'unit.emp_saboteur',
    age: 'future',
    height: 70,
    palette: { ...X, skin: 0xcfa98c, sleeve: charcoal, forearm: charcoal, glove: zone('metal2'), pants: charcoal, shin: charcoal, boot: zone('metal2') },
    head: 'future.head.grin',
    eyes: null,
    hat: [{ part: 'future.hood', tag: 'prop' }],
    torso: 'future.torso.suit',
    pelvis: 'future.pelvis.suit',
    weapon: { part: 'future.baton', rot: 100 },
    extraBones: [{ id: 'device', parent: 'torso', x: -11, y: -12 }],
    extras: [slot(sized('future.emp.device', 70 / 68), 'device', 2)],
    pose: { armF: -30, foreF: -50, armB: 14, foreB: -30, torso: 6 },
    attack: 'biped.attack.swing',
    ability: 'ability.emp',
    group: 'epic',
    size: 'medium',
  }),
  walker({
    id: 'unit.chrono_titan',
    age: 'future',
    palette: X,
    height: 200,
    center: 80 * TITAN_K,
    bones: scaleBones(
      [
        { id: 'hull', parent: 'spin', x: 0, y: 0 },
        { id: 'head', parent: 'hull', x: 2, y: -64 },
        { id: 'clock', parent: 'hull', x: 1, y: -30 },
        { id: 'legB', parent: 'hull', x: -12, y: 14 },
        { id: 'shinB', parent: 'legB', x: 0, y: 30 },
        { id: 'footB', parent: 'shinB', x: 0, y: 30 },
        { id: 'legF', parent: 'hull', x: 12, y: 14 },
        { id: 'shinF', parent: 'legF', x: 0, y: 30 },
        { id: 'footF', parent: 'shinF', x: 0, y: 30 },
        { id: 'armB', parent: 'hull', x: -32, y: -48, rot: 10 },
        { id: 'foreB', parent: 'armB', x: 0, y: 26, rot: -14 },
        { id: 'armF', parent: 'hull', x: 32, y: -48, rot: -12 },
        { id: 'foreF', parent: 'armF', x: 0, y: 26, rot: -18 },
      ],
      TITAN_K,
    ),
    slots: scaleSlots(
      [
        slot('future.titan.upperarm', 'armB', 3, { tone: 'back', noWidth: true }),
        slot('future.titan.fist', 'foreB', 4, { tone: 'back', noWidth: true }),
        slot('future.titan.thigh', 'legB', 5, { tone: 'back' }),
        slot('future.titan.shin', 'shinB', 6, { tone: 'back' }),
        slot('future.titan.foot', 'footB', 7, { tone: 'back' }),
        // A11 redundant team cue: a pennant on every heavy
        slot(sized('future.turret.flag', 1.5), 'hull', 9.5, { x: -24, y: -56, id: 'pennant', noWidth: true }),
        slot('future.titan.hull', 'hull', 10),
        slot('future.titan.clock', 'clock', 11),
        slot('future.titan.head', 'head', 11.5),
        slot('future.titan.thigh', 'legF', 12, { id: 'thighF' }),
        slot('future.titan.shin', 'shinF', 13, { id: 'shinFs' }),
        slot('future.titan.foot', 'footF', 14, { id: 'footFs' }),
        slot('future.titan.upperarm', 'armF', 15, { id: 'upperF', noWidth: true }),
        slot('future.titan.fist', 'foreF', 16, { tag: 'weapon', id: 'fistF' }),
      ],
      TITAN_K,
    ),
    attack: 'walker.attack.slam',
    ability: 'ability.time_stop',
    group: 'legendary',
    size: 'huge',
    legendary: true,
    legLen: 60 * TITAN_K,
    legDeg: 16,
    speed: 35,
  }),

  // W7 Future wave (CONTENT_PLAN 5.7): procedural fallbacks behind the Blender sheets
  biped({
    id: 'unit.android_pair',
    age: 'future',
    height: 66,
    palette: ANDROID,
    head: 'future.head.plain',
    eyes: null,
    hat: [{ part: 'future.helmet.trooper', tag: 'prop' }],
    torso: 'future.torso.suit',
    pelvis: 'future.pelvis.suit',
    weapon: { part: 'future.baton', rot: 100 },
    pose: { armF: -30, foreF: -50, armB: 10, foreB: -30 },
    attack: 'biped.attack.swing',
    group: 'infantry',
    size: 'small',
  }),
  biped({
    id: 'unit.barrier_trooper',
    age: 'future',
    height: 70,
    palette: armored,
    head: 'future.head.plain',
    eyes: null,
    hat: [{ part: 'future.helmet.knight', tag: 'prop' }],
    torso: 'future.torso.armor',
    pelvis: 'future.pelvis.armor',
    weapon: { part: sized('future.baton', 1.1), rot: 100 },
    offhand: { part: sized('future.capacitor', 1.4) },
    pose: { armF: -30, foreF: -50, armB: -40, foreB: -60 },
    attack: 'biped.attack.swing',
    ability: 'ability.shield_raise',
    group: 'infantry',
    size: 'small',
  }),
  vehicle({
    id: 'unit.hover_bike',
    age: 'future',
    palette: { ...X, skin: 0xcfa98c },
    height: 66,
    center: 20,
    bones: [
      { id: 'hull', parent: 'spin', x: 0, y: 10 },
      { id: 'pilot', parent: 'hull', x: -2, y: -30 },
      { id: 'lance', parent: 'pilot', x: 12, y: 4 },
      { id: 'flag1', parent: 'hull', x: -16, y: -22 },
    ],
    slots: [
      slot(sized('future.turret.flag', 1.1), 'flag1', 4, { noWidth: true }),
      slot(sized('future.drone.body', 1.1), 'hull', 10),
      slot(sized('future.mech.pilot', 1.8), 'pilot', 12, { tag: 'prop' }),
      slot(sized('future.photonblade', 0.9), 'lance', 13, { tag: 'weapon', noWidth: true, rot: 80 }),
    ],
    attack: 'vehicle.attack.ram',
    ability: 'ability.charge_lean',
    group: 'infantry',
    size: 'medium',
    wheelRadius: 6,
    speed: 110,
  }),
  biped({
    id: 'unit.needle_gunner',
    age: 'future',
    height: 66,
    palette: { ...armored, skin: 0xcfa98c },
    head: 'future.head.grin',
    eyes: 'shared.eyes.angry',
    hat: [{ part: 'future.helmet.trooper', tag: 'prop' }],
    torso: 'future.torso.suit',
    pelvis: 'future.pelvis.suit',
    weapon: { part: sized('future.plasmarifle', 0.85), rot: 180, y: 2, muzzle: { x: 0, y: -34 } },
    pose: { armF: -78, foreF: -12, armB: -64, foreB: -46 },
    attack: 'biped.attack.shoot',
    group: 'ranged',
    size: 'small',
    twirl: false,
  }),
  walker({
    id: 'unit.crab_mech',
    age: 'future',
    palette: { ...X, skin: 0xcfa98c },
    height: 100,
    center: 50 * CRAB_K,
    bones: scaleBones(
      [
        { id: 'hull', parent: 'spin', x: 0, y: 0 },
        { id: 'pilot', parent: 'hull', x: 10, y: -22 },
        { id: 'legB', parent: 'hull', x: -10, y: 6 },
        { id: 'shinB', parent: 'legB', x: 0, y: 20 },
        { id: 'footB', parent: 'shinB', x: 0, y: 20 },
        { id: 'legF', parent: 'hull', x: 10, y: 6 },
        { id: 'shinF', parent: 'legF', x: 0, y: 20 },
        { id: 'footF', parent: 'shinF', x: 0, y: 20 },
        { id: 'armB', parent: 'hull', x: -14, y: -16, rot: 40 },
        { id: 'foreB', parent: 'armB', x: 0, y: 16, rot: -60 },
        { id: 'armF', parent: 'hull', x: 18, y: -16, rot: -40 },
        { id: 'foreF', parent: 'armF', x: 0, y: 16, rot: -60 },
      ],
      CRAB_K,
    ),
    slots: scaleSlots(
      [
        slot('future.mech.upperarm', 'armB', 3, { tone: 'back', noWidth: true }),
        slot('future.mech.claw', 'foreB', 4, { tone: 'back', noWidth: true, id: 'clawB' }),
        slot('future.mech.thigh', 'legB', 5, { tone: 'back' }),
        slot('future.mech.shin', 'shinB', 6, { tone: 'back' }),
        slot('future.mech.foot', 'footB', 7, { tone: 'back' }),
        slot('future.mech.pilot', 'pilot', 9, { tag: 'prop' }),
        // A11 redundant team cue: a pennant on every heavy
        slot('future.turret.flag', 'hull', 9.5, { x: -16, y: -20, id: 'pennant', noWidth: true }),
        slot('future.mech.hull', 'hull', 10),
        slot('future.mech.thigh', 'legF', 12, { id: 'thighF' }),
        slot('future.mech.shin', 'shinF', 13, { id: 'shinFs' }),
        slot('future.mech.foot', 'footF', 14, { id: 'footFs' }),
        slot('future.mech.upperarm', 'armF', 15, { id: 'upperF', noWidth: true }),
        slot('future.mech.claw', 'foreF', 16, { tag: 'weapon', noWidth: true }),
      ],
      CRAB_K,
    ),
    attack: 'walker.attack.punch',
    group: 'heavy',
    size: 'large',
    legLen: 40 * CRAB_K,
    legDeg: 24,
    speed: 45,
  }),
  biped({
    id: 'unit.arc_lobber',
    age: 'future',
    height: 66,
    palette: { ...armored, skin: 0xa8876f },
    head: 'future.head.grin',
    eyes: 'shared.eyes.angry',
    hat: [{ part: 'future.helmet.rail', tag: 'prop' }],
    torso: 'future.torso.armor',
    pelvis: 'future.pelvis.armor',
    weapon: { part: sized('future.turret.mortar', 0.6), rot: 140, muzzle: { x: 0, y: -16 } },
    pose: { armF: 34, foreF: -96, armB: -40, foreB: -30 },
    attack: 'biped.attack.throw',
    group: 'ranged',
    size: 'small',
    twirl: false,
  }),
  biped({
    id: 'unit.plasma_lancer',
    age: 'future',
    height: 72,
    palette: armored,
    head: 'future.head.plain',
    eyes: null,
    hat: [{ part: 'future.helmet.knight', tag: 'prop' }],
    torso: 'future.torso.armor',
    pelvis: 'future.pelvis.armor',
    weapon: { part: sized('future.photonblade', 1.25), rot: 160 },
    extras: [slot('future.skirt', 'pelvis', 21)],
    pose: { armF: -32, foreF: -58, armB: -55, foreB: -40, legF: -10, legB: 8 },
    attack: 'biped.attack.thrust',
    ability: 'ability.shield_raise',
    group: 'antiArmor',
    size: 'medium',
  }),
  biped({
    id: 'unit.overclock_engineer',
    age: 'future',
    height: 68,
    palette: { ...X, skin: 0xcfa98c, sleeve: white, forearm: white, glove: zone('metal2'), pants: charcoal, shin: charcoal, boot: zone('metal2') },
    head: 'future.head.grin',
    eyes: 'shared.eyes.angry',
    hat: [{ part: 'future.hood', tag: 'prop' }],
    torso: 'future.torso.suit',
    back: [{ part: sized('future.capacitor', 0.8), x: -8, y: -10 }],
    pelvis: 'future.pelvis.suit',
    weapon: { part: 'future.baton', rot: 140, muzzle: { x: 0, y: -12 } },
    pose: { armF: -60, foreF: -30, armB: 14, foreB: -30 },
    attack: 'biped.attack.cast',
    ability: 'ability.beacon',
    group: 'support',
    size: 'small',
    twirl: false,
  }),
  biped({
    id: 'unit.holo_projector',
    age: 'future',
    height: 68,
    palette: { ...armored, skin: 0xe8c9ad },
    head: 'future.head.plain',
    eyes: 'shared.eyes.angry',
    hat: [{ part: 'future.helmet.trooper', tag: 'prop' }],
    torso: 'future.torso.suit',
    back: [{ part: sized('future.drone.emitter', 1.2), x: -10, y: -14 }],
    pelvis: 'future.pelvis.suit',
    weapon: { part: sized('future.plasmarifle', 0.7), rot: 180, y: 2, muzzle: { x: 0, y: -28 } },
    pose: { armF: -78, foreF: -12, armB: -64, foreB: -46 },
    attack: 'biped.attack.shoot',
    ability: 'ability.beacon',
    group: 'support',
    size: 'small',
    twirl: false,
  }),
  flyer({
    id: 'unit.jetpack_trooper',
    age: 'future',
    palette: { ...X, skin: 0xcfa98c },
    height: 52,
    center: 24,
    bones: [
      { id: 'body', parent: 'spin', x: 0, y: 0 },
      { id: 'pilot', parent: 'body', x: 2, y: -14 },
      { id: 'rotor', parent: 'body', x: -13, y: -6 },
      { id: 'rotorB', parent: 'body', x: 13, y: -6 },
      { id: 'emitter', parent: 'body', x: 4, y: 10 },
      { id: 'muzzle', parent: 'emitter', x: 6, y: 4 },
    ],
    slots: [
      slot('future.drone.pod', 'body', 8, { x: -13, y: -6, noWidth: true }),
      slot('future.drone.pod', 'body', 8, { x: 13, y: -6, id: 'podB', noWidth: true }),
      slot('future.drone.emitter', 'emitter', 9),
      slot(sized('future.turret.flag', 0.8), 'body', 7, { x: -10, y: -10, id: 'pennant', noWidth: true }),
      slot('future.drone.body', 'body', 10),
      slot('future.mech.pilot', 'pilot', 11, { tag: 'prop' }),
    ],
    muzzleBone: 'muzzle',
    attack: 'flyer.attack.gun',
    group: 'epic',
    size: 'medium',
    speed: 75,
  }),
  vehicle({
    id: 'unit.particle_cannon',
    age: 'future',
    palette: X,
    height: 92,
    center: 30,
    bones: [
      { id: 'hull', parent: 'spin', x: 0, y: 14 },
      { id: 'padB', parent: 'hull', x: -18, y: 8 },
      { id: 'padF', parent: 'hull', x: 16, y: 8 },
      { id: 'turret', parent: 'hull', x: -4, y: -22 },
      { id: 'barrel', parent: 'turret', x: 6, y: -12, rot: -12 },
      { id: 'muzzle', parent: 'barrel', x: 0, y: -56 },
      { id: 'flag1', parent: 'turret', x: -10, y: -12 },
    ],
    slots: [
      slot('future.turret.flag', 'flag1', 4, { noWidth: true }),
      slot('cosmic.hover.pad', 'padB', 8, { tone: 'back', id: 'padFar' }),
      slot('future.railgun', 'barrel', 9, { tag: 'weapon', noWidth: true }),
      slot('cosmic.hover.turret', 'turret', 10),
      slot('cosmic.hover.hull', 'hull', 12),
      slot('cosmic.hover.pad', 'padF', 13),
    ],
    muzzleBone: 'muzzle',
    attack: 'vehicle.attack.recoil',
    ability: 'ability.recoil',
    group: 'epic',
    size: 'large',
    speed: 40,
  }),
  biped({
    id: 'unit.overload_android',
    age: 'future',
    height: 74,
    palette: ANDROID,
    head: 'future.head.plain',
    eyes: null,
    hat: [{ part: 'future.helmet.knight', tag: 'prop' }],
    torso: 'future.torso.armor',
    pelvis: 'future.pelvis.armor',
    weapon: { part: sized('future.titan.fist', 0.4), rot: 90 },
    offhand: { part: sized('future.titan.fist', 0.4) },
    pose: { armF: -40, foreF: -60, armB: 20, foreB: -50, torso: 6 },
    attack: 'biped.attack.swing',
    ability: 'ability.roar',
    group: 'epic',
    size: 'medium',
  }),
  vehicle({
    id: 'unit.drone_carrier',
    age: 'future',
    palette: X,
    height: 177,
    center: 30 * CARRIER_K,
    bones: scaleBones(
      [
        { id: 'hull', parent: 'spin', x: 0, y: 14 },
        { id: 'padB', parent: 'hull', x: -18, y: 8 },
        { id: 'padF', parent: 'hull', x: 16, y: 8 },
        { id: 'turret', parent: 'hull', x: -4, y: -22 },
        { id: 'barrel', parent: 'turret', x: 10, y: -7 },
        { id: 'muzzle', parent: 'barrel', x: 32, y: 0 },
        { id: 'tower', parent: 'turret', x: -8, y: -8 },
        { id: 'deck', parent: 'tower', x: 0, y: -54 },
        { id: 'flag1', parent: 'tower', x: -6, y: -40 },
      ],
      CARRIER_K,
    ),
    slots: scaleSlots(
      [
        slot('future.turret.flag', 'flag1', 4, { noWidth: true, id: 'pennant' }),
        slot('cosmic.hover.pad', 'padB', 8, { tone: 'back', id: 'padFar' }),
        slot('future.turret.laser', 'barrel', 9, { tag: 'weapon', noWidth: true }),
        slot('cosmic.hover.turret', 'turret', 10),
        slot('cosmic.hover.hull', 'hull', 12),
        slot('cosmic.hover.pad', 'padF', 13),
        slot(sized('future.turret.pylon', 1.5), 'tower', 13.5, { noWidth: true }),
        slot('future.drone.body', 'deck', 14, { noWidth: true }),
      ],
      CARRIER_K,
    ),
    muzzleBone: 'muzzle',
    attack: 'vehicle.attack.recoil',
    ability: 'ability.beacon',
    group: 'legendary',
    size: 'huge',
    legendary: true,
    speed: 30,
  }),
  biped({
    id: 'unit.holo_decoy',
    age: 'future',
    height: 66,
    palette: { ...armored, sleeve: X.glass, forearm: X.glass, shin: X.glass },
    head: 'future.head.plain',
    eyes: null,
    hat: [{ part: 'future.helmet.knight', tag: 'prop' }],
    torso: 'future.torso.armor',
    pelvis: 'future.pelvis.armor',
    weapon: { part: 'future.photonblade', rot: 100 },
    pose: { armF: -30, foreF: -50, armB: 10, foreB: -30 },
    attack: 'biped.attack.swing',
    group: 'infantry',
    size: 'small',
  }),
  flyer({
    id: 'unit.attack_drone',
    age: 'future',
    palette: X,
    height: 34,
    center: 15,
    bones: [
      { id: 'body', parent: 'spin', x: 0, y: 0 },
      { id: 'rotor', parent: 'body', x: -12, y: -10 },
      { id: 'rotorB', parent: 'body', x: 12, y: -10 },
      { id: 'emitter', parent: 'body', x: 0, y: 9 },
      { id: 'muzzle', parent: 'emitter', x: 0, y: 5 },
    ],
    slots: [
      slot('future.drone.pod', 'body', 8, { x: -12, y: -10, noWidth: true }),
      slot('future.drone.pod', 'body', 8, { x: 12, y: -10, id: 'podB', noWidth: true }),
      slot('future.drone.emitter', 'emitter', 9),
      slot(sized('future.drone.body', 0.9), 'body', 10),
      slot('future.drone.blade', 'rotor', 11, { y: -3, noWidth: true }),
      slot('future.drone.blade', 'rotorB', 11, { y: -3, id: 'bladeB', noWidth: true }),
    ],
    muzzleBone: 'muzzle',
    attack: 'flyer.attack.gun',
    group: 'epic',
    size: 'small',
    speed: 90,
  }),
];

export const FUTURE_TURRETS: TurretPuppet[] = [
  turret({
    id: 'turret.pulse_laser',
    age: 'future',
    palette: X,
    height: 34,
    bones: [
      { id: 'pivot', parent: 'root', x: 0, y: -26 },
      { id: 'barrel', parent: 'pivot', x: 0, y: 0 },
      { id: 'muzzle', parent: 'pivot', x: 19, y: 0 },
    ],
    slots: [slot('future.turret.flag', 'root', 5, { x: -14, y: -6 }), slot('future.turret.pylon', 'root', 10), slot('future.turret.laser', 'barrel', 12)],
    aim: [-35, 25],
  }),
  turret({
    id: 'turret.arc_coil',
    age: 'future',
    palette: X,
    height: 46,
    bones: [
      { id: 'pivot', parent: 'root', x: 0, y: 0 },
      { id: 'muzzle', parent: 'pivot', x: 0, y: -37 },
    ],
    slots: [slot('future.turret.flag', 'root', 5, { x: -16, y: -6 }), slot('future.turret.coil', 'pivot', 10)],
    aim: [0, 0],
  }),
  turret({
    id: 'turret.plasma_mortar',
    age: 'future',
    palette: X,
    height: 34,
    bones: [
      { id: 'pivot', parent: 'root', x: 0, y: -10, rot: -55 },
      { id: 'barrel', parent: 'pivot', x: 0, y: 0 },
      { id: 'muzzle', parent: 'pivot', x: 27, y: 0 },
    ],
    slots: [slot('future.turret.flag', 'root', 5, { x: -16, y: -6 }), slot('future.turret.mortar', 'barrel', 11), slot('future.turret.mortarBase', 'root', 12)],
    aim: [0, 0],
  }),
  turret({
    id: 'turret.gravity_well',
    age: 'future',
    palette: X,
    height: 48,
    bones: [
      { id: 'pivot', parent: 'root', x: 0, y: 0 },
      { id: 'orb', parent: 'pivot', x: 0, y: -26 },
      { id: 'muzzle', parent: 'pivot', x: 0, y: -26 },
    ],
    slots: [slot('future.turret.flag', 'root', 5, { x: -18, y: -6 }), slot('future.turret.orb', 'orb', 9), slot('future.turret.ring', 'pivot', 10)],
    aim: [0, 0],
  }),
  turret({
    id: 'turret.cryo_pod',
    age: 'future',
    palette: X,
    height: 36,
    bones: [
      { id: 'pivot', parent: 'root', x: 0, y: -24 },
      { id: 'barrel', parent: 'pivot', x: 0, y: 0 },
      { id: 'muzzle', parent: 'pivot', x: 16, y: 0 },
    ],
    slots: [slot('future.turret.flag', 'root', 5, { x: -14, y: -6 }), slot('future.turret.pylon', 'root', 10), slot(sized('future.turret.orb', 0.9), 'barrel', 12)],
    aim: [-35, 25],
  }),
  turret({
    id: 'turret.tractor_beam',
    age: 'future',
    palette: X,
    height: 38,
    bones: [
      { id: 'pivot', parent: 'root', x: 0, y: -28 },
      { id: 'barrel', parent: 'pivot', x: 0, y: 0 },
      { id: 'muzzle', parent: 'pivot', x: 18, y: 0 },
    ],
    slots: [slot('future.turret.flag', 'root', 5, { x: -16, y: -6 }), slot('future.turret.pylon', 'root', 10), slot(sized('future.turret.laser', 1.1), 'barrel', 12)],
    aim: [-35, 25],
  }),
];

export const FUTURE_BASE: BasePuppet = base({
  id: 'base.future',
  age: 'future',
  palette: X,
  height: 300,
  width: 150,
  bones: [
    { id: 'body', parent: 'root', x: 0, y: 0 },
    { id: 'flag1', parent: 'body', x: -66, y: -150 },
    { id: 'flag2', parent: 'body', x: -140, y: -120 },
    { id: 'torch1', parent: 'body', x: -60, y: -52 },
    { id: 'torch2', parent: 'body', x: -16, y: -52 },
    { id: 'smoke', parent: 'body', x: -90, y: -220 },
  ],
  slots: [
    slot('future.base.antenna', 'body', 0.5, { x: -100, y: -296 }),
    slot('future.base.spire', 'body', 1),
    slot('future.base.chunk', 'body', 1.1, { when: { crumbleMax: 1 } }),
    slot('future.base.holo', 'flag2', 1.5, { when: { crumbleMax: 2 } }),
    slot('future.base.wing', 'body', 2),
    slot('future.base.gate', 'body', 3),
    slot('future.base.crack1', 'body', 4, { when: { crumbleMin: 1 } }),
    slot('future.base.crack2', 'body', 4.1, { when: { crumbleMin: 2 } }),
    slot('future.base.holo', 'flag1', 5, { when: { crumbleMax: 2 }, id: 'holo1' }),
    slot('future.base.light', 'torch1', 9),
    slot('future.base.light', 'torch2', 9),
    slot('future.base.ledge', 'body', 10, { x: -8, y: -40 }),
    slot('future.base.ledge', 'body', 10, { x: -10, y: -84, id: 'ledge2' }),
    slot('future.base.ledge', 'body', 10, { x: -14, y: -128, id: 'ledge3' }),
    slot('future.base.ledge', 'body', 10, { x: -56, y: -186, id: 'ledge4' }),
    slot('future.base.treasury1', 'body', 12, { x: -140, y: 0, when: { treasuryMin: 1 } }),
    slot('future.base.treasury2', 'body', 12, { x: -122, y: 0, when: { treasuryMin: 2 } }),
    slot('future.base.treasury3', 'body', 12.1, { x: -100, y: 0, when: { treasuryMin: 3 } }),
    slot('future.base.rubble', 'body', 13, { when: { crumbleMin: 2 } }),
    slot('future.base.smoke', 'smoke', 14, { when: { crumbleMin: 3 } }),
  ],
  mounts: [
    { x: -8, y: -45 },
    { x: -10, y: -89 },
    { x: -14, y: -133 },
    { x: -56, y: -191 },
  ],
  hornAt: { x: -100, y: -330 },
  flags: ['flag1', 'flag2'],
  flickers: ['torch1', 'torch2'],
});
