/**
 * Gunpowder Age puppets (DESIGN A5.4 units and turrets, A11 art direction, the Star Fort base).
 * Each entry is a procedural visual source keyed like its manifest id. The Cuirassier's horse reuses
 * the Medieval horse parts with its own palette.
 */
import { AGE_ZONES } from '../palette';
import '../parts/gunpowder';
import '../parts/medieval';
import { sized } from '../parts/registry';
import { base, type BasePuppet } from '../rigs/base';
import { biped } from '../rigs/biped';
import { slot } from '../rigs/common';
import { flyer, vehicle } from '../rigs/machines';
import { rider } from '../rigs/rider';
import { turret, type TurretPuppet } from '../rigs/turret';
import type { PuppetDef } from '../types';

const Z = AGE_ZONES.gunpowder;
const zone = (k: string): number => Z[k] ?? 0x888888;

/** Extra gunpowder zones (under the colour rule's 40% saturation in the team hue bands). */
const X = {
  ...Z,
  apron: 0xf2ecdc,
  mark: 0xb04a4a,
  hat: 0x3a332e,
  iron: 0x3e3b3a,
  spark: 0xfff1b8,
  bronze: 0x9a8a62,
  wicker: 0x9a8468,
  wicker2: 0x7a6650,
  rocket: 0xd9d0bc,
  plaster: 0xe6dcc8,
  roof: 0x6a5446,
  grass: 0x7d8a5a,
  glow: 0xf2d59a,
  coin: 0xe6c45c,
  smoke: 0x9a948c,
  hoof: 0x3a3430,
  snout: 0x8a7e76,
};

const cream = zone('cloth2');
/** Soldiers: team coat sleeves are drawn by the coat; arms in cream cuffs, gaiters and black shoes. */
const soldier = { ...X, sleeve: cream, forearm: cream, glove: zone('skin'), pants: cream, shin: 0x3a3632, boot: 0x2e2a28 };

export const GUNPOWDER_UNITS: PuppetDef[] = [
  biped({
    id: 'unit.corsair',
    age: 'gunpowder',
    palette: { ...X, skin: 0xa8876f, hair: 0x2e2826, sleeve: cream, forearm: 0xa8876f, glove: 0xa8876f, pants: zone('cloth3'), shin: zone('cloth3'), boot: 0x2e2a28 },
    head: 'gunpowder.head.pirate',
    eyes: 'shared.eyes.angry',
    hat: [{ part: 'gunpowder.bandana', tag: 'prop' }, { part: 'gunpowder.eyepatch' }, { part: 'gunpowder.earring' }],
    torso: 'gunpowder.torso.pirate',
    pelvis: 'gunpowder.pelvis.sash',
    weapon: { part: 'gunpowder.cutlass', rot: 100 },
    offhand: { part: 'gunpowder.hook', rot: 30, y: 2 },
    pose: { armF: -30, foreF: -50, armB: 14, foreB: -34 },
    attack: 'biped.attack.swing',
    ability: 'ability.hook_throw',
    group: 'infantry',
    size: 'small',
  }),
  biped({
    id: 'unit.fusilier',
    age: 'gunpowder',
    palette: { ...soldier, hair: 0x5a4a3e },
    head: 'gunpowder.head.soldier',
    hat: [{ part: 'gunpowder.tricorne', tag: 'prop' }],
    hairBack: [{ part: 'gunpowder.hair.queue' }],
    torso: 'gunpowder.torso.coat',
    pelvis: 'gunpowder.pelvis.coat',
    weapon: { part: 'gunpowder.musket', rot: 180, x: 0, y: 2, muzzle: { x: 0, y: -44 } },
    pose: { armF: -78, foreF: -12, armB: -64, foreB: -46 },
    attack: 'biped.attack.shoot',
    group: 'ranged',
    size: 'small',
    twirl: false,
  }),
  rider({
    id: 'unit.cuirassier',
    age: 'gunpowder',
    height: 112,
    mount: {
      palette: { ...X, fur: 0x4a423c, fur2: 0x3a3430, hair: 0x2a2624 },
      body: 'medieval.horse.body',
      bodyHeight: 42,
      legFront: 'medieval.horse.leg.front',
      legBack: 'medieval.horse.leg.back',
      legLen: 32,
      frontX: 14,
      backX: -14,
      legY: 10,
      farDx: -5,
      neck: { x: 15.4, y: -12, rot: -8 },
      head: { part: 'medieval.horse.head', x: 0, y: 0 },
      eyes: { part: 'shared.eyes.beast', x: 12, y: -25 },
      tail: { part: 'medieval.horse.tail', x: -16, y: -8, rot: 14 },
      saddle: { x: -6, y: -16 },
      extras: [
        slot('gunpowder.horse.shabraque', 'body', 21),
        slot('gunpowder.horse.bridle', 'snout', 31),
        slot('medieval.horse.saddle', 'saddle', 24),
        // A11 redundant team cue: a pennant on every heavy (a guidon in a holster behind the saddle,
        // mirrored so it trails behind the rider instead of hiding behind them)
        slot(sized('gunpowder.cannon.pennant', 1.4), 'body', 20.5, { x: -20, y: -12, sx: -1, noWidth: true }),
      ],
      headTopY: -112,
    },
    rider: {
      palette: { ...soldier, sleeve: 0xefe6cf, forearm: 0xefe6cf, glove: 0xefe6cf, pants: 0xefe6cf, shin: 0x2e2a28, boot: 0x2e2a28, hair: 0x3f3530 },
      head: 'gunpowder.head.soldier',
      eyes: 'shared.eyes.angry',
      hat: [{ part: 'gunpowder.helmet.crest', tag: 'prop' }, { part: 'gunpowder.moustache' }],
      torso: 'gunpowder.torso.cuirass',
      pelvis: 'gunpowder.pelvis.breeches',
      weapon: { part: 'gunpowder.sabre', rot: 96 },
      pose: { armF: -40, foreF: -50, armB: -10, foreB: -30 },
    },
    attack: 'rider.attack.swing',
    ability: 'ability.charge_lean',
    group: 'heavy',
    size: 'large',
  }),
  biped({
    id: 'unit.grenadier',
    age: 'gunpowder',
    height: 70,
    palette: { ...soldier, hair: 0x6b5445, skin: 0xe8c9ad, glove: 0xe8c9ad },
    head: 'gunpowder.head.grenadier',
    eyes: 'shared.eyes.angry',
    hat: [{ part: 'gunpowder.mitre', tag: 'prop' }],
    torso: 'gunpowder.torso.coat',
    pelvis: 'gunpowder.pelvis.coat',
    arm: { hand: 'shared.hand' },
    weapon: { part: 'gunpowder.grenade', rot: 20, muzzle: { x: 0, y: -4 } },
    pose: { armF: 34, foreF: -96, armB: -40, foreB: -30 },
    attack: 'biped.attack.throw',
    group: 'antiArmor',
    size: 'medium',
    twirl: false,
  }),
  biped({
    id: 'unit.field_surgeon',
    age: 'gunpowder',
    height: 66,
    palette: { ...soldier, hair: 0x8a8078, skin: 0xe8c9ad, glove: 0xe8c9ad },
    head: 'gunpowder.head.doctor',
    hat: [{ part: 'gunpowder.tricorne', tag: 'prop' }, { part: 'gunpowder.moustache' }],
    torso: 'gunpowder.torso.surgeon',
    pelvis: 'gunpowder.pelvis.coat',
    weapon: { part: 'gunpowder.pistol', rot: 180, muzzle: { x: 0, y: -12 } },
    offhand: { part: 'gunpowder.medbag', rot: 0, y: 2 },
    pose: { armF: -78, foreF: -12, armB: 12, foreB: -12 },
    attack: 'biped.attack.shoot',
    group: 'support',
    size: 'small',
    twirl: false,
  }),
  vehicle({
    id: 'unit.bronze_cannon',
    age: 'gunpowder',
    palette: { ...X, skin: 0xcfa98c, hair: 0x3f3530, fur: 0x9a8e80 },
    height: 76,
    center: 30,
    bones: [
      { id: 'hull', parent: 'spin', x: 0, y: 30 },
      { id: 'gunner', parent: 'hull', x: -24, y: -20 },
      { id: 'wheel1', parent: 'hull', x: 4, y: -17.5 },
      { id: 'turret', parent: 'hull', x: 8, y: -33 },
      { id: 'barrel', parent: 'turret', x: 0, y: 0, rot: -8 },
      { id: 'muzzle', parent: 'barrel', x: 38, y: 0 },
      { id: 'flag1', parent: 'hull', x: -36, y: -10 },
    ],
    slots: [
      slot('gunpowder.cannon.pennant', 'flag1', 3, { noWidth: true }),
      slot(sized('gunpowder.cannon.gunner', 1.25), 'gunner', 5, { tag: 'prop' }),
      slot(sized('gunpowder.cannon.carriage', 1.25), 'hull', 10),
      slot(sized('gunpowder.cannon.barrel', 1.25), 'barrel', 12, { tag: 'weapon' }),
      slot(sized('gunpowder.cannon.wheel', 1.25), 'wheel1', 14),
    ],
    muzzleBone: 'muzzle',
    attack: 'vehicle.attack.recoil',
    ability: 'ability.recoil',
    group: 'epic',
    size: 'large',
    wheelRadius: 17.5,
    speed: 45,
  }),
  flyer({
    id: 'unit.balloon_admiral',
    age: 'gunpowder',
    palette: { ...X, skin: 0xe8c9ad, hair: 0xd9d4c6 },
    height: 176,
    center: 80,
    bones: [
      { id: 'body', parent: 'spin', x: 0, y: 40 },
      { id: 'gondola', parent: 'body', x: 0, y: 16 },
      { id: 'admiral', parent: 'gondola', x: -4, y: 2 },
      { id: 'hatch', parent: 'gondola', x: 0, y: 22 },
      { id: 'muzzle', parent: 'gondola', x: 0, y: 28 },
    ],
    slots: [
      slot(sized('gunpowder.balloon.envelope', 1.12), 'body', 10),
      slot('gunpowder.balloon.ropes', 'body', 11),
      slot('gunpowder.balloon.admiral', 'admiral', 12, { tag: 'prop' }),
      slot('gunpowder.telescope', 'admiral', 12.5, { x: 12, y: -14, rot: 70, noWidth: true }),
      slot('gunpowder.balloon.gondola', 'gondola', 13),
      slot('gunpowder.balloon.hatch', 'hatch', 12.8),
      slot('gunpowder.balloon.bomb', 'gondola', 12.6, { x: 12, y: -6 }),
    ],
    muzzleBone: 'muzzle',
    attack: 'flyer.attack.drop',
    ability: 'ability.bomb_drop',
    group: 'legendary',
    size: 'huge',
    legendary: true,
    speed: 45,
  }),
];

export const GUNPOWDER_TURRETS: TurretPuppet[] = [
  turret({
    id: 'turret.swivel_gun',
    age: 'gunpowder',
    palette: X,
    height: 40,
    bones: [
      { id: 'pivot', parent: 'root', x: 0, y: -27 },
      { id: 'barrel', parent: 'pivot', x: 0, y: 0 },
      { id: 'muzzle', parent: 'pivot', x: 19, y: 0 },
    ],
    slots: [
      slot('gunpowder.turret.flag', 'root', 5, { x: -14, y: -14 }),
      slot('gunpowder.turret.gabion', 'root', 8, { x: 2 }),
      slot('gunpowder.turret.post', 'root', 10),
      slot('gunpowder.turret.swivel', 'barrel', 12),
    ],
    aim: [-40, 30],
  }),
  turret({
    id: 'turret.grapeshot_gun',
    age: 'gunpowder',
    palette: X,
    height: 36,
    bones: [
      { id: 'pivot', parent: 'root', x: 2, y: -18 },
      { id: 'barrel', parent: 'pivot', x: 0, y: 0 },
      { id: 'muzzle', parent: 'pivot', x: 19, y: 0 },
    ],
    slots: [
      slot('gunpowder.turret.flag', 'root', 5, { x: -16, y: -10 }),
      slot('gunpowder.turret.sled', 'root', 10),
      slot(sized('gunpowder.turret.grapeshot', 1.15), 'barrel', 12),
    ],
    aim: [-25, 15],
  }),
  turret({
    id: 'turret.congreve_rack',
    age: 'gunpowder',
    palette: X,
    height: 46,
    bones: [
      { id: 'pivot', parent: 'root', x: -2, y: -26, rot: -22 },
      { id: 'barrel', parent: 'pivot', x: 0, y: 0 },
      { id: 'muzzle', parent: 'pivot', x: 20, y: 0 },
    ],
    slots: [
      slot('gunpowder.turret.flag', 'root', 5, { x: -16, y: -8 }),
      slot('gunpowder.turret.rackFrame', 'root', 10),
      slot('gunpowder.turret.rockets', 'barrel', 12),
    ],
    aim: [-30, 0],
  }),
  turret({
    id: 'turret.chainshot_cannon',
    age: 'gunpowder',
    palette: X,
    height: 34,
    bones: [
      { id: 'pivot', parent: 'root', x: 0, y: -18 },
      { id: 'barrel', parent: 'pivot', x: 0, y: 0 },
      { id: 'muzzle', parent: 'pivot', x: 36, y: 0 },
    ],
    slots: [
      slot('gunpowder.turret.flag', 'root', 5, { x: -16, y: -10 }),
      slot('gunpowder.turret.truck', 'root', 10),
      slot('gunpowder.turret.longgun', 'barrel', 12),
    ],
    aim: [-20, 15],
  }),
];

export const GUNPOWDER_BASE: BasePuppet = base({
  id: 'base.gunpowder',
  age: 'gunpowder',
  palette: X,
  height: 240,
  width: 160,
  bones: [
    { id: 'body', parent: 'root', x: 0, y: 0 },
    { id: 'flag1', parent: 'body', x: -30, y: -134 },
    { id: 'torch1', parent: 'body', x: -74, y: -44 },
    { id: 'torch2', parent: 'body', x: -30, y: -44 },
    { id: 'smoke', parent: 'body', x: -80, y: -190 },
  ],
  slots: [
    slot('gunpowder.base.keep', 'body', 1),
    slot('gunpowder.base.chunk', 'body', 1.1, { when: { crumbleMax: 1 } }),
    slot('gunpowder.base.cannon', 'body', 1.5, { x: -120, y: -100 }),
    slot('gunpowder.base.rampart', 'body', 2),
    slot('gunpowder.base.embrasure', 'body', 2.5, { x: -110, y: -96 }),
    slot('gunpowder.base.gate', 'body', 3),
    slot('gunpowder.base.crack1', 'body', 4, { when: { crumbleMin: 1 } }),
    slot('gunpowder.base.crack2', 'body', 4.1, { when: { crumbleMin: 2 } }),
    slot('gunpowder.base.flag', 'flag1', 5, { when: { crumbleMax: 2 } }),
    slot('gunpowder.base.lantern', 'torch1', 9),
    slot('gunpowder.base.lantern', 'torch2', 9),
    slot('gunpowder.base.ledge', 'body', 10, { x: -12, y: -40 }),
    slot('gunpowder.base.ledge', 'body', 10, { x: -16, y: -84, id: 'ledge2' }),
    slot('gunpowder.base.ledge', 'body', 10, { x: -26, y: -128, id: 'ledge3' }),
    slot('gunpowder.base.ledge', 'body', 10, { x: -44, y: -172, id: 'ledge4' }),
    slot('gunpowder.base.treasury1', 'body', 12, { x: -132, y: 0, when: { treasuryMin: 1 } }),
    slot('gunpowder.base.treasury2', 'body', 12, { x: -108, y: 0, when: { treasuryMin: 2 } }),
    slot('gunpowder.base.treasury3', 'body', 12.1, { x: -88, y: 0, when: { treasuryMin: 3 } }),
    slot('gunpowder.base.rubble', 'body', 13, { when: { crumbleMin: 2 } }),
    slot('gunpowder.base.smoke', 'smoke', 14, { when: { crumbleMin: 3 } }),
  ],
  mounts: [
    { x: -12, y: -46 },
    { x: -16, y: -90 },
    { x: -26, y: -134 },
    { x: -44, y: -178 },
  ],
  hornAt: { x: -85, y: -262 },
  flags: ['flag1'],
  flickers: ['torch1', 'torch2'],
});
