/**
 * Medieval Age puppets (DESIGN A5.3 units and turrets, A11 art direction, the Keep base).
 * Each entry is a procedural visual source keyed like its manifest id.
 */
import { AGE_ZONES } from '../palette';
import '../parts/medieval';
import { sized } from '../parts/registry';
import { base, type BasePuppet } from '../rigs/base';
import { biped } from '../rigs/biped';
import { slot } from '../rigs/common';
import { vehicle } from '../rigs/machines';
import { rider } from '../rigs/rider';
import { turret, type TurretPuppet } from '../rigs/turret';
import type { PuppetDef } from '../types';

const Z = AGE_ZONES.medieval;
const zone = (k: string): number => Z[k] ?? 0x888888;

/** Extra medieval zones (all under the colour rule's 40% saturation in the team hue bands). */
const X = {
  ...Z,
  robe: 0x7a6858,
  hide: 0x9a8468,
  hoof: 0x4a403a,
  snout: 0xb09a8c,
  feather: 0xf2efe6,
  feather2: 0xd9d4c6,
  beak: 0xe39a3c,
  pitch: 0x3a342e,
  fire: 0xf2b45a,
  bread: 0xc4a47a,
  bread2: 0x9a7c58,
  sack: 0xc8b48c,
  coin: 0xe6c45c,
  glow: 0xf2d59a,
  smoke: 0x9a948c,
};

/** Soldiers: mail sleeves, leather gloves, slate hose, leather boots. */
const soldier = { ...X, sleeve: zone('metal2'), forearm: zone('metal2'), glove: zone('leather'), pants: zone('cloth'), shin: zone('cloth'), boot: zone('leather') };
const knight = { ...soldier, sleeve: zone('metal'), forearm: zone('metal'), glove: zone('metal2'), pants: zone('metal2'), shin: zone('metal'), boot: zone('metal2') };

export const MEDIEVAL_UNITS: PuppetDef[] = [
  biped({
    id: 'unit.footman',
    age: 'medieval',
    palette: soldier,
    head: 'medieval.head.soldier',
    eyes: 'shared.eyes.angry',
    hat: [{ part: 'medieval.helm.nasal', tag: 'prop' }],
    torso: 'medieval.torso.tabard',
    pelvis: 'medieval.pelvis.tabard',
    weapon: { part: 'medieval.sword', rot: 100 },
    offhand: { part: 'medieval.shield.kite', z: 45, rot: 62, x: 1, y: 1, tone: undefined },
    pose: { armF: -30, foreF: -50, armB: -8, foreB: -54 },
    attack: 'biped.attack.swing',
    ability: 'ability.shield_raise',
    group: 'infantry',
    size: 'small',
  }),
  biped({
    id: 'unit.longbowman',
    age: 'medieval',
    height: 66,
    palette: { ...soldier, skin: 0xcfa98c, sleeve: zone('leather'), forearm: 0xcfa98c, glove: zone('leather'), hair: 0x6b5445 },
    head: 'medieval.head.archer',
    hat: [{ part: 'medieval.hood', tag: 'prop' }],
    torso: 'medieval.torso.jerkin',
    back: [{ part: 'medieval.quiver', x: -8, y: -12, rot: -24 }],
    pelvis: 'medieval.pelvis.hose',
    weapon: { part: 'medieval.longbow', x: 1, muzzle: { x: 6, y: 0 } },
    offhand: { part: 'medieval.arrow', rot: 190, z: 54, y: 1, tone: undefined, id: 'arrow' },
    extraBones: [
      { id: 'stringU', parent: 'handF', x: -1.2, y: -25.8 },
      { id: 'stringL', parent: 'handF', x: -1.2, y: 25.8, rot: 180 },
    ],
    extras: [
      slot(sized('medieval.bowstring', 66 / 68), 'stringU', 52.4, { id: 'stringU', noWidth: true }),
      slot(sized('medieval.bowstring', 66 / 68), 'stringL', 52.4, { id: 'stringL', noWidth: true }),
    ],
    pose: { armF: -80, foreF: -5, handF: 85, armB: -70, foreB: -30 },
    attack: 'biped.attack.bow',
    group: 'ranged',
    size: 'small',
    twirl: false,
  }),
  rider({
    id: 'unit.destrier_knight',
    age: 'medieval',
    height: 112,
    mount: {
      palette: { ...X, fur: 0x7d6452, fur2: 0x5e4a3c, hair: 0x3a302a },
      body: 'medieval.horse.body',
      bodyHeight: 42,
      legFront: 'medieval.horse.leg.front',
      legBack: 'medieval.horse.leg.back',
      legLen: 32,
      frontX: 14,
      backX: -14,
      legY: 10,
      farDx: -5,
      neck: { x: 17, y: -12, rot: -8 },
      head: { part: 'medieval.horse.head', x: 0, y: 0 },
      eyes: { part: 'shared.eyes.beast', x: 12, y: -25 },
      tail: { part: 'medieval.horse.tail', x: -17, y: -8, rot: 12 },
      saddle: { x: -6, y: -16 },
      extras: [slot('medieval.horse.caparison', 'body', 21), slot('medieval.horse.chanfron', 'snout', 31), slot('medieval.horse.saddle', 'saddle', 24)],
      headTopY: -112,
    },
    rider: {
      palette: knight,
      head: 'medieval.head.knight',
      eyes: null,
      hat: [{ part: 'medieval.helm.great', tag: 'prop' }],
      torso: 'medieval.torso.plate',
      pelvis: 'medieval.pelvis.hose',
      weapon: { part: 'medieval.lance', rot: 164, y: 2 },
      offhand: { part: 'medieval.shield.heater', rot: 40, x: 2, z: 44 },
      pose: { armF: 8, foreF: -84, armB: -10, foreB: -30 },
    },
    attack: 'rider.attack.lance',
    ability: 'ability.charge_lean',
    group: 'heavy',
    size: 'large',
  }),
  biped({
    id: 'unit.pikeman',
    age: 'medieval',
    height: 72,
    palette: { ...soldier, sleeve: zone('cloth3'), forearm: zone('cloth3'), skin: 0xa8876f, hair: 0x3a302a },
    head: 'medieval.head.soldier',
    hat: [{ part: 'medieval.helm.morion', tag: 'prop' }],
    torso: 'medieval.torso.gambeson',
    pelvis: 'medieval.pelvis.hose',
    weapon: { part: 'medieval.pike', rot: 166 },
    pose: { armF: -32, foreF: -58, armB: -55, foreB: -40, legF: -10, legB: 8 },
    attack: 'biped.attack.thrust',
    group: 'antiArmor',
    size: 'medium',
  }),
  biped({
    id: 'unit.friar',
    age: 'medieval',
    height: 64,
    palette: { ...X, skin: 0xe8c9ad, hair: 0x8a7a6a, sleeve: 0x7a6858, forearm: 0x7a6858, glove: 0xe8c9ad, pants: 0x7a6858, shin: 0x7a6858, boot: zone('leather') },
    head: 'medieval.head.friar',
    hat: [{ part: 'medieval.tonsure' }],
    hairBack: [{ part: 'medieval.cowl' }],
    torso: 'medieval.torso.habit',
    pelvis: 'medieval.pelvis.robe',
    arm: { hand: 'shared.hand.open' },
    weapon: { part: 'medieval.loaf', rot: 20, y: -2, muzzle: { x: 0, y: -1 } },
    offhand: { part: 'medieval.staff', rot: -16, y: 1 },
    pose: { armF: 12, foreF: -62, armB: 36, foreB: -20 },
    attack: 'biped.attack.throw',
    group: 'support',
    size: 'small',
    twirl: false,
  }),
  vehicle({
    id: 'unit.battering_ram',
    age: 'medieval',
    palette: X,
    height: 106,
    center: 40,
    bones: [
      { id: 'hull', parent: 'spin', x: 0, y: 40 },
      { id: 'wheel1', parent: 'hull', x: -18, y: -11 },
      { id: 'wheel2', parent: 'hull', x: 14, y: -11 },
      { id: 'log', parent: 'hull', x: -2, y: -30 },
      { id: 'flag1', parent: 'hull', x: -3, y: -80 },
    ],
    slots: [
      slot('medieval.ram.banner', 'flag1', 4, { noWidth: true }),
      slot('medieval.ram.chains', 'hull', 8, { x: 0, y: -30 }),
      slot('medieval.ram.log', 'log', 9, { tag: 'weapon' }),
      slot('medieval.ram.hull', 'hull', 10),
      slot('medieval.ram.wheel', 'wheel1', 12),
      slot('medieval.ram.wheel', 'wheel2', 12, { id: 'wheelB' }),
    ],
    attack: 'vehicle.attack.ram',
    ability: 'ability.ram_swing',
    group: 'epic',
    size: 'large',
    wheelRadius: 11,
    speed: 45,
  }),
  rider({
    id: 'unit.ursa_paladin',
    age: 'medieval',
    height: 196,
    mount: {
      palette: { ...X, fur: 0x6e5a4a, fur2: 0x54463b, snout: 0x9a8a7c },
      body: 'medieval.bear.body',
      bodyHeight: 70,
      legFront: 'medieval.bear.leg.front',
      legBack: 'medieval.bear.leg.back',
      legLen: 50,
      frontX: 22,
      backX: -24,
      legY: 20,
      farDx: -9,
      neck: { x: 22, y: -18 },
      head: { part: 'medieval.bear.head', x: 0, y: 0 },
      jaw: { part: 'medieval.bear.jaw', x: 0, y: 0 },
      eyes: { part: 'shared.eyes.beast*1.5', x: 27, y: -22 },
      tail: { part: 'medieval.bear.tail', x: -38, y: -14 },
      saddle: { x: -6, y: -44 },
      extras: [slot('medieval.bear.barding', 'body', 21), slot('medieval.bear.helm', 'snout', 31.5), slot('medieval.bear.saddle', 'saddle', 24)],
      headTopY: -196,
    },
    rider: {
      height: 85,
      palette: knight,
      head: 'medieval.head.knight',
      eyes: 'shared.eyes.angry',
      hat: [{ part: 'medieval.helm.paladin', tag: 'prop' }],
      torso: 'medieval.torso.plate',
      pelvis: 'medieval.pelvis.hose',
      weapon: { part: 'medieval.greatsword', rot: 95 },
      offhand: { part: 'medieval.shield.heater', rot: 60, x: 1 },
      pose: { armF: -20, foreF: -50, armB: -30, foreB: -40 },
    },
    attack: 'rider.attack.swing',
    ability: 'ability.roar',
    group: 'legendary',
    size: 'huge',
    legendary: true,
  }),
];

export const MEDIEVAL_TURRETS: TurretPuppet[] = [
  turret({
    id: 'turret.crossbow_nest',
    age: 'medieval',
    palette: X,
    height: 44,
    bones: [
      { id: 'pivot', parent: 'root', x: 0, y: -24 },
      { id: 'barrel', parent: 'pivot', x: 0, y: 0 },
      { id: 'muzzle', parent: 'pivot', x: 24, y: 0 },
    ],
    slots: [
      slot('medieval.turret.flag', 'root', 5, { x: -14, y: -18 }),
      slot('medieval.turret.nest', 'root', 10),
      slot('medieval.turret.crossbow', 'barrel', 11),
      slot('medieval.turret.nestShield', 'root', 12, { x: 9, y: -2 }),
    ],
    aim: [-40, 30],
  }),
  turret({
    id: 'turret.pitch_cauldron',
    age: 'medieval',
    palette: X,
    height: 52,
    bones: [
      { id: 'pivot', parent: 'root', x: 0, y: 0 },
      { id: 'bucket', parent: 'pivot', x: 6, y: -27 },
      { id: 'muzzle', parent: 'bucket', x: 12, y: 2 },
    ],
    slots: [
      slot('medieval.turret.bracket', 'pivot', 10),
      slot('medieval.turret.fire', 'pivot', 11, { x: 6, y: -1 }),
      slot('medieval.turret.cauldron', 'bucket', 12),
      slot('medieval.turret.flag', 'root', 5, { x: -18, y: -30 }),
    ],
    aim: [0, 0],
    fire: 'turret.fire.pour',
  }),
  turret({
    id: 'turret.trebuchet',
    age: 'medieval',
    palette: X,
    height: 74,
    bones: [
      { id: 'pivot', parent: 'root', x: 0, y: -40 },
      { id: 'arm', parent: 'pivot', x: 0, y: 0, rot: -28 },
      { id: 'muzzle', parent: 'root', x: 6, y: -78 },
    ],
    slots: [
      slot('medieval.turret.flag', 'root', 5, { x: -20, y: -4 }),
      slot('medieval.turret.trebArm', 'arm', 9),
      slot('medieval.turret.trebFrame', 'root', 10),
    ],
    aim: [0, 0],
    fire: 'turret.fire.sling',
  }),
  turret({
    id: 'turret.honk_ballista',
    age: 'medieval',
    palette: X,
    height: 48,
    bones: [
      { id: 'pivot', parent: 'root', x: 0, y: -22 },
      { id: 'barrel', parent: 'pivot', x: 0, y: 0 },
      { id: 'muzzle', parent: 'pivot', x: 24, y: -4 },
    ],
    slots: [
      slot('medieval.turret.flag', 'root', 5, { x: -16, y: -6 }),
      slot('medieval.turret.ballistaBase', 'root', 10),
      slot('medieval.turret.ballista', 'pivot', 11),
      slot('medieval.turret.goose', 'barrel', 12, { x: -2, y: -3 }),
    ],
    aim: [-35, 25],
  }),
];

export const MEDIEVAL_BASE: BasePuppet = base({
  id: 'base.medieval',
  age: 'medieval',
  palette: X,
  height: 318,
  width: 158,
  bones: [
    { id: 'body', parent: 'root', x: 0, y: 0 },
    { id: 'flag1', parent: 'body', x: -60, y: -194 },
    { id: 'flag2', parent: 'body', x: -119, y: -318 },
    { id: 'torch1', parent: 'body', x: -80, y: -34 },
    { id: 'torch2', parent: 'body', x: -28, y: -34 },
    { id: 'smoke', parent: 'body', x: -70, y: -200 },
  ],
  slots: [
    slot('medieval.base.banner', 'flag2', 0),
    slot('medieval.base.tower', 'body', 1),
    slot('medieval.base.roof', 'body', 1.2),
    slot('medieval.base.wall', 'body', 2),
    slot('medieval.base.chunk', 'body', 2.1, { when: { crumbleMax: 1 } }),
    slot('medieval.base.gate', 'body', 3),
    slot('medieval.base.window', 'body', 3.2, { x: -70, y: -120 }),
    slot('medieval.base.window', 'body', 3.2, { x: -40, y: -100, id: 'window2' }),
    slot('medieval.base.window', 'body', 3.2, { x: -119, y: -210, id: 'window3' }),
    slot('medieval.base.crack1', 'body', 4, { when: { crumbleMin: 1 } }),
    slot('medieval.base.crack2', 'body', 4.1, { when: { crumbleMin: 2 } }),
    slot('medieval.base.hanging', 'body', 5, { x: -119, y: -170, when: { crumbleMax: 2 } }),
    slot('medieval.base.banner', 'flag1', 5.2, { when: { crumbleMax: 2 } }),
    slot('medieval.base.torch', 'torch1', 9),
    slot('medieval.base.torch', 'torch2', 9),
    slot('medieval.base.ledge', 'body', 10, { x: -12, y: -56 }),
    slot('medieval.base.ledge', 'body', 10, { x: -12, y: -100, id: 'ledge2' }),
    slot('medieval.base.ledge', 'body', 10, { x: -12, y: -144, id: 'ledge3' }),
    slot('medieval.base.ledge', 'body', 10, { x: -20, y: -196, id: 'ledge4' }),
    slot('medieval.base.treasury1', 'body', 12, { x: -134, y: 0, when: { treasuryMin: 1 } }),
    slot('medieval.base.treasury2', 'body', 12, { x: -110, y: 0, when: { treasuryMin: 2 } }),
    slot('medieval.base.treasury3', 'body', 12.1, { x: -134, y: -12, when: { treasuryMin: 3 } }),
    slot('medieval.base.rubble', 'body', 13, { when: { crumbleMin: 2 } }),
    slot('medieval.base.smoke', 'smoke', 14, { when: { crumbleMin: 3 } }),
  ],
  mounts: [
    { x: -12, y: -62 },
    { x: -12, y: -106 },
    { x: -12, y: -150 },
    { x: -20, y: -202 },
  ],
  hornAt: { x: -90, y: -236 },
  flags: ['flag1', 'flag2'],
  flickers: ['torch1', 'torch2'],
});
