/**
 * Stone Age puppets (DESIGN A5.2 units and turrets, A11 art direction, Cave Hold base).
 * Each entry is a procedural visual source keyed like its manifest id.
 */
import { AGE_ZONES } from '../palette';
import '../parts/stone';
import { sized } from '../parts/registry';
import { base, type BasePuppet } from '../rigs/base';
import { biped } from '../rigs/biped';
import { slot } from '../rigs/common';
import { quadruped } from '../rigs/quadruped';
import { turret, type TurretPuppet } from '../rigs/turret';
import type { PuppetDef } from '../types';

const Z = AGE_ZONES.stone;
const skin = Z['skin'] ?? 0;
/** Bare-limbed cave folk: arms and legs are skin, feet bare. */
const cave = { ...Z, sleeve: skin, forearm: skin, shin: skin, pants: skin, glove: skin };

export const STONE_UNITS: PuppetDef[] = [
  biped({
    id: 'unit.bonker',
    age: 'stone',
    palette: cave,
    head: 'stone.head.brute',
    eyes: 'shared.eyes.angry',
    hat: [{ part: 'stone.hair.shaggy' }],
    torso: 'stone.torso.tunic',
    pelvis: 'stone.pelvis.loin',
    leg: { lower: 'shared.leg.lower.bare' },
    weapon: { part: 'stone.club', rot: 104, tag: 'prop' },
    pose: { armF: -35, foreF: -45, armB: 18, foreB: -26 },
    attack: 'biped.attack.swing',
    group: 'infantry',
    size: 'small',
  }),
  biped({
    id: 'unit.pebbler',
    age: 'stone',
    height: 64,
    palette: { ...cave, skin: 0xe8c9ad, sleeve: 0xe8c9ad, forearm: 0xe8c9ad, shin: 0xe8c9ad, pants: 0xe8c9ad, glove: 0xe8c9ad, hair: 0x6b5445 },
    head: 'stone.head.plain',
    hat: [{ part: 'stone.hair.topknot', tag: 'prop' }],
    torso: 'stone.torso.hunter',
    pelvis: 'stone.pelvis.loin',
    leg: { lower: 'shared.leg.lower.bare' },
    weapon: { part: 'stone.sling', rot: 160, muzzle: { x: -1.4, y: -17.4 } },
    extras: [slot(sized('stone.pouch', 64 / 68), 'pelvis', 21, { x: -7, y: 1 })],
    pose: { armF: -28, foreF: -30, armB: 20, foreB: -30 },
    attack: 'biped.attack.throw',
    group: 'ranged',
    size: 'small',
  }),
  biped({
    id: 'unit.spear_hunter',
    age: 'stone',
    height: 72,
    palette: { ...cave, skin: 0xa8876f, sleeve: 0xa8876f, forearm: 0xa8876f, shin: 0xa8876f, pants: 0xa8876f, glove: 0xa8876f, hair: 0x3a302a },
    head: 'stone.head.hunter',
    eyes: 'shared.eyes.angry',
    hat: [{ part: 'stone.hair.feather', tag: 'prop' }],
    torso: 'stone.torso.hunter',
    pelvis: 'stone.pelvis.loin',
    leg: { lower: 'shared.leg.lower.bare' },
    weapon: { part: 'stone.spear', rot: 168, y: 0 },
    pose: { armF: -32, foreF: -58, armB: -55, foreB: -40, legF: -10, legB: 8 },
    attack: 'biped.attack.thrust',
    group: 'antiArmor',
    size: 'medium',
  }),
  biped({
    id: 'unit.drum_shaman',
    age: 'stone',
    height: 66,
    palette: { ...cave, skin: 0x86695a, sleeve: 0x86695a, forearm: 0x86695a, shin: 0x86695a, pants: 0x86695a, glove: 0x86695a },
    head: 'stone.head.elder',
    hat: [{ part: 'stone.beard.grey' }, { part: 'stone.mask.skull', tag: 'prop' }],
    torso: 'stone.torso.shaman',
    pelvis: 'stone.pelvis.loin',
    leg: { lower: 'shared.leg.lower.bare' },
    weapon: { part: 'stone.drumstick', rot: 20, muzzle: { x: 0, y: -12 } },
    offhand: { part: 'stone.drum', z: 45, rot: -20, x: 2, y: 4, tone: undefined },
    pose: { armF: -60, foreF: -50, armB: -40, foreB: -70 },
    attack: 'biped.attack.drum',
    group: 'support',
    size: 'small',
  }),
  quadruped({
    id: 'unit.tuskback',
    age: 'stone',
    palette: { ...Z, fur: 0x7d6858, fur2: 0x5e4f43, snout: 0xc4a898, hair: 0x3f352f },
    height: 104,
    body: 'stone.boar.body',
    bodyHeight: 48,
    legFront: 'stone.boar.leg.front',
    legBack: 'stone.boar.leg.back',
    legLen: 30,
    frontX: 11,
    backX: -12,
    legY: 18,
    neck: { x: 8, y: -4 },
    head: { part: 'stone.boar.head', x: 0, y: 0 },
    jaw: { part: 'stone.boar.jaw', x: 0, y: 0 },
    eyes: { part: 'shared.eyes.beast', x: 13, y: -7 },
    tail: { part: 'stone.boar.tail', x: -20, y: -6, rot: 35 },
    extras: [slot('stone.boar.crest', 'body', 19), slot('stone.pennant', 'body', 18.5, { x: -10, y: -22, tag: 'prop', noWidth: true })],
    attack: 'quadruped.attack.gore',
    ability: 'ability.charge_lean',
    group: 'heavy',
    size: 'large',
  }),
  quadruped({
    id: 'unit.sabertooth',
    age: 'stone',
    palette: { ...Z, fur: 0xa08c70, fur2: 0x74604f, hair: 0x4d4038 },
    height: 60,
    body: 'stone.cat.body',
    bodyHeight: 30,
    legFront: 'stone.cat.leg.front',
    legBack: 'stone.cat.leg.back',
    legLen: 22,
    frontX: 9,
    backX: -10,
    legY: 8,
    farDx: -4,
    neck: { x: 4, y: -8 },
    head: { part: 'stone.cat.head', x: 0, y: 0 },
    jaw: { part: 'stone.cat.jaw', x: 0, y: 0 },
    eyes: { part: 'shared.eyes.beast', x: 10, y: -4 },
    tail: { part: 'stone.cat.tail', x: -12, y: -6, rot: 75 },
    attack: 'quadruped.attack.bite',
    ability: 'ability.pounce',
    group: 'epic',
    size: 'medium',
  }),
  quadruped({
    id: 'unit.mammoth_matriarch',
    age: 'stone',
    palette: { ...Z, fur: 0x86705e, fur2: 0x5f4f43, hair: 0x4a3d34 },
    height: 196,
    body: sized('stone.mammoth.body', 0.9),
    bodyHeight: 76,
    legFront: 'stone.mammoth.leg.front',
    legBack: 'stone.mammoth.leg.back',
    legLen: 56,
    frontX: 26,
    backX: -26,
    legY: 20,
    farDx: -6,
    neck: { x: 18, y: -24 },
    head: { part: 'stone.mammoth.head', x: 0, y: 0 },
    eyes: { part: 'shared.eyes.beast', x: 22, y: -22 },
    trunk: { part: 'stone.mammoth.trunk', x: 26, y: 2 },
    tail: { part: 'stone.mammoth.tail', x: -40, y: -12, rot: 10 },
    extraBones: [
      { id: 'rider1', parent: 'body', x: -22, y: -50 },
      { id: 'rider2', parent: 'body', x: 2, y: -52 },
      { id: 'howdah', parent: 'body', x: 0, y: -46 },
    ],
    extras: [
      slot('stone.mammoth.tusk', 'snout', 33, { x: 14, y: 6, tag: 'weapon' }),
      slot('stone.mammoth.rider', 'rider1', 24, { tag: 'prop' }),
      slot('stone.mammoth.rider', 'rider2', 24.1),
      slot('stone.mammoth.howdah', 'howdah', 26, { x: 5 }),
      slot(sized('stone.pennant', 1.6), 'howdah', 25.5, { x: 22, y: -10, noWidth: true }),
    ],
    attack: 'quadruped.attack.stomp',
    ability: 'ability.stomp_riders',
    group: 'legendary',
    size: 'huge',
    legendary: true,
    legDeg: 16,
  }),
  biped({
    id: 'unit.training_dummy',
    age: 'stone',
    height: 60,
    palette: { ...Z, straw: 0xd6c08e, sack: 0xc8b48c, pants: 0xc8b48c, shin: 0xc8b48c, boot: 0x8a7560, sleeve: 0xd6c08e, forearm: 0xd6c08e, glove: 0xd6c08e },
    head: 'stone.dummy.head',
    eyes: null,
    torso: 'stone.dummy.torso',
    torsoOver: [{ part: 'stone.dummy.scarf', y: -20 }],
    pelvis: 'stone.pelvis.loin',
    weapon: { part: 'stone.dummy.sword', rot: 60, tag: 'prop' },
    pose: { armF: -30, foreF: -40, armB: 30, foreB: 10 },
    attack: 'biped.attack.swing',
    group: 'infantry',
    size: 'small',
  }),
];

const turretZ = { ...Z, hive: 0xcdb98a, hive2: 0xa89464, toad: 0x7e9a5a, toad2: 0x5d7443, glow: 0xede3c8 };

export const STONE_TURRETS: TurretPuppet[] = [
  turret({
    id: 'turret.rock_tosser',
    age: 'stone',
    palette: turretZ,
    height: 48,
    bones: [
      { id: 'pivot', parent: 'root', x: 0, y: -20 },
      { id: 'arm', parent: 'pivot', x: 0, y: 0, rot: -12 },
      { id: 'muzzle', parent: 'root', x: 10, y: -46 },
    ],
    slots: [slot('stone.turret.frame', 'root', 10), slot('stone.turret.catapultArm', 'arm', 12), slot('stone.turret.flag', 'root', 5, { x: -14, y: -16 })],
    aim: [0, 0],
  }),
  turret({
    id: 'turret.angry_beehive',
    age: 'stone',
    palette: turretZ,
    height: 54,
    bones: [
      { id: 'pivot', parent: 'root', x: 0, y: -20 },
      { id: 'muzzle', parent: 'pivot', x: 6, y: -12 },
      { id: 'bee1', parent: 'pivot', x: 16, y: -26 },
      { id: 'bee2', parent: 'pivot', x: -14, y: -30 },
      { id: 'bee3', parent: 'pivot', x: 20, y: -10 },
    ],
    slots: [
      slot('stone.turret.stump', 'root', 10),
      slot('stone.turret.hive', 'pivot', 12),
      slot('stone.turret.bee', 'bee1', 14),
      slot('stone.turret.bee', 'bee2', 14),
      slot('stone.turret.bee', 'bee3', 14),
      slot('stone.turret.flag', 'root', 5, { x: -12, y: -18 }),
    ],
    aim: [0, 0],
  }),
  turret({
    id: 'turret.log_roller',
    age: 'stone',
    palette: turretZ,
    height: 40,
    bones: [
      { id: 'pivot', parent: 'root', x: 0, y: 0 },
      { id: 'barrel', parent: 'pivot', x: 10, y: -32 },
      { id: 'muzzle', parent: 'root', x: 22, y: -8 },
    ],
    slots: [slot('stone.turret.ramp', 'pivot', 10), slot('stone.turret.log', 'barrel', 12), slot('stone.turret.flag', 'root', 5, { x: -16, y: -8 })],
    aim: [0, 0],
  }),
  turret({
    id: 'turret.grumpy_toad',
    age: 'stone',
    palette: turretZ,
    height: 50,
    bones: [
      { id: 'pivot', parent: 'root', x: 0, y: -20 },
      { id: 'lid', parent: 'pivot', x: 6, y: -8 },
      { id: 'muzzle', parent: 'pivot', x: 20, y: -8 },
    ],
    slots: [
      slot('stone.turret.stump', 'root', 10),
      slot('stone.turret.toad', 'pivot', 12),
      slot('stone.turret.toadMouth', 'lid', 13),
      slot('stone.turret.flag', 'root', 5, { x: -12, y: -18 }),
    ],
    aim: [-18, 18],
  }),
];

const baseZ = { ...Z, fire: 0xf2b45a, berry: 0x9a3a5a, meat: 0xb87a6a, smoke: 0x9a948c };

export const STONE_BASE: BasePuppet = base({
  id: 'base.stone',
  age: 'stone',
  palette: baseZ,
  height: 232,
  width: 152,
  bones: [
    { id: 'body', parent: 'root', x: 0, y: 0 },
    { id: 'flag1', parent: 'body', x: -60, y: -224 },
    { id: 'flag2', parent: 'body', x: -118, y: -184 },
    { id: 'torch1', parent: 'body', x: -44, y: -40 },
    { id: 'torch2', parent: 'body', x: 2, y: -46 },
    { id: 'smoke', parent: 'body', x: -60, y: -200 },
  ],
  slots: [
    slot('stone.base.banner', 'flag2', 0),
    slot('stone.base.rock', 'body', 1),
    slot('stone.base.chunk', 'body', 1.5, { when: { crumbleMax: 1 } }),
    slot('stone.base.cave', 'body', 2),
    slot('stone.base.crack1', 'body', 3, { when: { crumbleMin: 1 } }),
    slot('stone.base.crack2', 'body', 3.1, { when: { crumbleMin: 2 } }),
    slot('stone.base.banner', 'flag1', 4, { when: { crumbleMax: 2 } }),
    slot('stone.base.skull', 'body', 6, { x: -76, y: -84 }),
    slot('stone.base.palisade', 'body', 8),
    slot('stone.base.torch', 'torch1', 9),
    slot('stone.base.torch', 'torch2', 9),
    slot('stone.base.ledge', 'body', 10, { x: -10, y: -58 }),
    slot('stone.base.ledge', 'body', 10, { x: -14, y: -104, id: 'ledge2' }),
    slot('stone.base.ledge', 'body', 10, { x: -20, y: -148, id: 'ledge3' }),
    slot('stone.base.ledge', 'body', 10, { x: -30, y: -192, id: 'ledge4' }),
    slot('stone.base.treasury1', 'body', 12, { x: -128, y: 0, when: { treasuryMin: 1 } }),
    slot('stone.base.treasury2', 'body', 12, { x: -100, y: 0, when: { treasuryMin: 2 } }),
    slot('stone.base.treasury3', 'body', 11, { x: -136, y: 0, when: { treasuryMin: 3 } }),
    slot('stone.base.rubble', 'body', 13, { when: { crumbleMin: 2 } }),
    slot('stone.base.smoke', 'smoke', 14, { when: { crumbleMin: 3 } }),
  ],
  mounts: [
    { x: -10, y: -64 },
    { x: -14, y: -110 },
    { x: -20, y: -154 },
    { x: -30, y: -198 },
  ],
  hornAt: { x: -70, y: -250 },
  flags: ['flag1', 'flag2'],
  flickers: ['torch1', 'torch2'],
});
