/**
 * Generated by `tools/audio/build.py` from the renders in `tools/audio`. Do not edit by hand:
 * change the sound design or the arrangements there and rebuild (see tools/audio/README.md).
 *
 * - `SFX_SHEETS`: one Ogg Opus sprite sheet per sound group, paths relative to the site base;
 *   `alt` is the same sheet as AAC (.m4a) and `sync` the time (s) where the sync burst at the
 *   start of the sheet is detected, so a decoder's start delay can be measured and undone.
 * - `SFX_FILES`: per sound id, its sheet and each variant's [offset, duration] in seconds.
 * - `MUSIC_FILES`: per music cue, stinger and layer stem, the file and, for loops, the loop
 *   window (`loopStart`, `loopLength` in seconds; any window of that length inside the file
 *   loops seamlessly); `alt` is the AAC (.m4a) copy. `stinger.<name>.k<n>` are the stingers
 *   recorded n semitones up (the key of the age the battle ended in).
 */

export interface SfxSheetFile {
  src: string;
  bytes: number;
  seconds: number;
  alt?: string;
  sync?: number;
}

export interface SfxFileEntry {
  sheet: string;
  /** [offset, duration] in seconds per variant. */
  variants: readonly (readonly [number, number])[];
}

export interface MusicFile {
  src: string;
  bytes: number;
  seconds: number;
  loopStart?: number;
  loopLength?: number;
  alt?: string;
}

export const SFX_BYTES = 1438274;
export const MUSIC_BYTES = 6730878;

export const SFX_SHEETS: Readonly<Record<string, SfxSheetFile>> = {
  ui: { src: "audio/sfx/ui.e81e775f.ogg", bytes: 26764, seconds: 5.216, alt: "audio/sfx/ui.99255a2e.m4a", sync: 0.02031 },
  battle: { src: "audio/sfx/battle.e4f0e090.ogg", bytes: 210409, seconds: 41.708, alt: "audio/sfx/battle.dae00932.m4a", sync: 0.02031 },
  stone: { src: "audio/sfx/stone.c8b32aea.ogg", bytes: 80488, seconds: 15.984, alt: "audio/sfx/stone.fd48fae3.m4a", sync: 0.02031 },
  bronze: { src: "audio/sfx/bronze.b90d5016.ogg", bytes: 104462, seconds: 20.458, alt: "audio/sfx/bronze.eca1f1af.m4a", sync: 0.02031 },
  medieval: { src: "audio/sfx/medieval.87b5b561.ogg", bytes: 53006, seconds: 10.383, alt: "audio/sfx/medieval.e95d8e90.m4a", sync: 0.02031 },
  match: { src: "audio/sfx/match.b895d388.ogg", bytes: 226807, seconds: 44.521, alt: "audio/sfx/match.3d3d65f1.m4a", sync: 0.02031 },
  gunpowder: { src: "audio/sfx/gunpowder.255f508c.ogg", bytes: 108853, seconds: 21.267, alt: "audio/sfx/gunpowder.cdfe9ee5.m4a", sync: 0.02031 },
  industrial: { src: "audio/sfx/industrial.fe60a263.ogg", bytes: 111569, seconds: 21.89, alt: "audio/sfx/industrial.87f6b26c.m4a", sync: 0.02031 },
  modern: { src: "audio/sfx/modern.24d81b7f.ogg", bytes: 72908, seconds: 14.41, alt: "audio/sfx/modern.eb04a7cd.m4a", sync: 0.02031 },
  future: { src: "audio/sfx/future.1483ac88.ogg", bytes: 91316, seconds: 17.904, alt: "audio/sfx/future.cf3467c8.m4a", sync: 0.02031 },
  cosmic: { src: "audio/sfx/cosmic.5823bf10.ogg", bytes: 104067, seconds: 20.554, alt: "audio/sfx/cosmic.bf886a1d.m4a", sync: 0.02031 },
  capsule: { src: "audio/sfx/capsule.fca2ee66.ogg", bytes: 247625, seconds: 48.968, alt: "audio/sfx/capsule.a942a98d.m4a", sync: 0.02031 },
};

export const SFX_FILES: Readonly<Record<string, SfxFileEntry>> = {
  ui_click: { sheet: "ui", variants: [[0.15, 0.09], [0.29, 0.09], [0.43, 0.09]] },
  ui_hover: { sheet: "ui", variants: [[0.57, 0.025], [0.645, 0.025], [0.72, 0.025]] },
  ui_deny: { sheet: "ui", variants: [[0.795, 0.24], [1.085, 0.24], [1.375, 0.24]] },
  ui_toggle: { sheet: "ui", variants: [[1.665, 0.105], [1.82, 0.105], [1.975, 0.105]] },
  ui_tab: { sheet: "ui", variants: [[2.13, 0.09688], [2.27687, 0.09433], [2.42121, 0.09467]] },
  ui_confirm: { sheet: "ui", variants: [[2.56588, 1.02], [3.63587, 1.02]] },
  meter_pip: { sheet: "ui", variants: [[4.70587, 0.12], [4.87587, 0.12], [5.04587, 0.12]] },
  spawn_pop: { sheet: "battle", variants: [[0.15, 0.18], [0.38, 0.18], [0.61, 0.18]] },
  spawn_heavy: { sheet: "battle", variants: [[0.84, 0.589], [1.479, 0.56617], [2.09517, 0.56304]] },
  step_heavy: { sheet: "battle", variants: [[2.70821, 0.25], [3.00821, 0.25], [3.30821, 0.25]] },
  swing_whoosh: { sheet: "battle", variants: [[3.60821, 0.1659], [3.8241, 0.16723], [4.04133, 0.16485]] },
  hit_blunt: { sheet: "battle", variants: [[4.25619, 0.2], [4.50619, 0.2], [4.75619, 0.2]] },
  hit_slash: { sheet: "battle", variants: [[5.00619, 0.14], [5.19619, 0.14], [5.38619, 0.14]] },
  hit_pierce: { sheet: "battle", variants: [[5.57619, 0.1], [5.72619, 0.1], [5.87619, 0.1]] },
  hit_bullet: { sheet: "battle", variants: [[6.02619, 0.125], [6.20119, 0.1016], [6.35279, 0.18]] },
  hit_laser: { sheet: "battle", variants: [[6.58279, 0.12], [6.75279, 0.12], [6.92279, 0.12]] },
  hit_heavy: { sheet: "battle", variants: [[7.09279, 0.422], [7.56479, 0.45215], [8.06694, 0.45319]] },
  hit_effective: { sheet: "battle", variants: [[8.57013, 0.304], [8.92413, 0.304], [9.27812, 0.304]] },
  explosion_s: { sheet: "battle", variants: [[9.63213, 0.79785], [10.47998, 0.77148], [11.30146, 0.72208]] },
  explosion_m: { sheet: "battle", variants: [[12.07354, 1.174], [13.29754, 1.20533], [14.55288, 1.15977]] },
  die_bio: { sheet: "battle", variants: [[15.76265, 0.31], [16.12265, 0.31], [16.48265, 0.31]] },
  die_mech: { sheet: "battle", variants: [[16.84265, 0.74194], [17.63458, 0.76148], [18.44606, 0.73217]] },
  prop_drop: { sheet: "battle", variants: [[19.22823, 0.233], [19.51123, 0.233], [19.79423, 0.233]] },
  heal_tick: { sheet: "battle", variants: [[20.07723, 0.35], [20.47723, 0.35], [20.87723, 0.35]] },
  shield_up: { sheet: "battle", variants: [[21.27723, 0.6], [21.92723, 0.6], [22.57723, 0.6]] },
  turret_build: { sheet: "battle", variants: [[23.22723, 0.8], [24.07723, 0.8], [24.92723, 0.8]] },
  turret_sell: { sheet: "battle", variants: [[25.77723, 0.58], [26.40723, 0.58], [27.03723, 0.58]] },
  turret_upgrade: { sheet: "battle", variants: [[27.66723, 0.68542], [28.40265, 0.68708]] },
  slot_buy: { sheet: "battle", variants: [[29.13973, 0.45], [29.63973, 0.45]] },
  base_hit: { sheet: "battle", variants: [[30.13973, 0.52569], [30.71542, 0.53038], [31.29579, 0.52054]] },
  coin_gain: { sheet: "battle", variants: [[31.86633, 0.68004], [32.59638, 0.67437], [33.32075, 0.65885]] },
  xp_tick: { sheet: "battle", variants: [[34.0296, 0.07], [34.1496, 0.07], [34.2696, 0.07]] },
  evolve_ready: { sheet: "battle", variants: [[34.3896, 1.22865]] },
  power_ready: { sheet: "battle", variants: [[35.66825, 0.77958]] },
  power_telegraph: { sheet: "battle", variants: [[36.49783, 1.0], [37.54783, 1.0]] },
  emote_pop: { sheet: "battle", variants: [[38.59783, 0.08], [38.72783, 0.08], [38.85783, 0.08]] },
  alert_base: { sheet: "battle", variants: [[38.98783, 1.31], [40.34783, 1.31]] },
  shot_sling: { sheet: "stone", variants: [[0.15, 0.13], [0.33, 0.13], [0.51, 0.13]] },
  shot_catapult: { sheet: "stone", variants: [[0.69, 0.58048], [1.32048, 0.57002], [1.9405, 0.58377]] },
  bee_buzz: { sheet: "stone", variants: [[2.57427, 0.4], [3.02427, 0.4], [3.47427, 0.4]] },
  log_roll: { sheet: "stone", variants: [[3.92427, 0.7], [4.67427, 0.69996], [5.42423, 0.7]] },
  toad_tongue: { sheet: "stone", variants: [[6.17423, 0.22], [6.44423, 0.22], [6.71423, 0.22]] },
  pw_stampede: { sheet: "stone", variants: [[6.98423, 2.0], [9.03423, 2.0]] },
  pw_meteor: { sheet: "stone", variants: [[11.08423, 2.4], [13.53423, 2.4]] },
  shot_javelin: { sheet: "bronze", variants: [[0.15, 0.265], [0.465, 0.265], [0.78, 0.265]] },
  shot_scorpion: { sheet: "bronze", variants: [[1.095, 0.55431], [1.69931, 0.56058], [2.3099, 0.54929]] },
  stomp_colossus: { sheet: "bronze", variants: [[2.90919, 1.13975], [4.09894, 1.03342], [5.18235, 1.09356]] },
  mirror_beam: { sheet: "bronze", variants: [[6.32592, 0.26], [6.63592, 0.26], [6.94592, 0.26]] },
  gorgon_gaze: { sheet: "bronze", variants: [[7.25592, 0.95715], [8.26306, 0.96708]] },
  pw_wave: { sheet: "bronze", variants: [[9.28015, 2.46531], [11.79546, 2.46273]] },
  pw_aegis: { sheet: "bronze", variants: [[14.30819, 2.0], [16.35819, 2.0]] },
  evolve_fanfare_bronze: { sheet: "bronze", variants: [[18.40819, 2.0]] },
  shot_bow: { sheet: "medieval", variants: [[0.15, 0.25], [0.45, 0.25], [0.75, 0.25]] },
  shot_crossbow: { sheet: "medieval", variants: [[1.05, 0.256], [1.356, 0.256], [1.662, 0.256]] },
  cauldron_pour: { sheet: "medieval", variants: [[1.968, 0.8], [2.818, 0.8], [3.668, 0.8]] },
  goose_honk: { sheet: "medieval", variants: [[4.518, 0.22], [4.788, 0.22], [5.058, 0.22]] },
  pw_arrows: { sheet: "medieval", variants: [[5.328, 1.55615], [6.93415, 1.54856]] },
  pw_decree: { sheet: "medieval", variants: [[8.53271, 1.8]] },
  spawn_legendary: { sheet: "match", variants: [[0.15, 1.8], [2.0, 1.8]] },
  explosion_l: { sheet: "match", variants: [[3.85, 1.69071], [5.59071, 1.7276], [7.36831, 1.67825]] },
  base_crumble: { sheet: "match", variants: [[9.09656, 1.34046], [10.48702, 1.32958]] },
  base_destroyed: { sheet: "match", variants: [[11.8666, 2.85]] },
  treasury_up: { sheet: "match", variants: [[14.7666, 0.75], [15.5666, 0.75]] },
  evolve_riser: { sheet: "match", variants: [[16.3666, 2.5]] },
  evolve_fanfare_stone: { sheet: "match", variants: [[18.9166, 1.97567]] },
  evolve_fanfare_medieval: { sheet: "match", variants: [[20.94227, 2.0]] },
  evolve_fanfare_gunpowder: { sheet: "match", variants: [[22.99227, 2.0]] },
  evolve_fanfare_modern: { sheet: "match", variants: [[25.04227, 2.0]] },
  evolve_fanfare_future: { sheet: "match", variants: [[27.09227, 2.0]] },
  evolve_enemy: { sheet: "match", variants: [[29.14227, 1.6]] },
  last_stand_armed: { sheet: "match", variants: [[30.79227, 1.4]] },
  last_stand_charge: { sheet: "match", variants: [[32.24227, 1.0]] },
  last_stand_fire: { sheet: "match", variants: [[33.29227, 1.35248]] },
  overdrive_horn: { sheet: "match", variants: [[34.69475, 1.44898]] },
  siege_bell: { sheet: "match", variants: [[36.19373, 3.4]] },
  victory_jingle: { sheet: "match", variants: [[39.64373, 2.17754]] },
  defeat_jingle: { sheet: "match", variants: [[41.87127, 2.6]] },
  shot_musket: { sheet: "gunpowder", variants: [[0.15, 0.74296], [0.94296, 0.71083], [1.70379, 0.71544]] },
  shot_lob: { sheet: "gunpowder", variants: [[2.46923, 0.25], [2.76923, 0.25], [3.06923, 0.25]] },
  shot_cannon: { sheet: "gunpowder", variants: [[3.36923, 1.29579], [4.71502, 1.41375], [6.17877, 1.36598]] },
  shot_grapeshot: { sheet: "gunpowder", variants: [[7.59475, 0.78412], [8.42887, 0.79448], [9.27335, 0.76513]] },
  shot_rocket: { sheet: "gunpowder", variants: [[10.08848, 0.56], [10.69848, 0.56], [11.30848, 0.56]] },
  bomb_whistle: { sheet: "gunpowder", variants: [[11.91848, 0.7], [12.66848, 0.7]] },
  pw_smoke: { sheet: "gunpowder", variants: [[13.41848, 1.75], [15.21848, 1.75]] },
  pw_broadside: { sheet: "gunpowder", variants: [[17.01848, 2.07633], [19.14481, 2.07185]] },
  shot_carbine: { sheet: "industrial", variants: [[0.15, 0.56377], [0.76377, 0.56898], [1.38275, 0.54696]] },
  shot_harpoon: { sheet: "industrial", variants: [[1.97971, 0.43], [2.45971, 0.43], [2.93971, 0.43]] },
  flare_pop: { sheet: "industrial", variants: [[3.41971, 0.53], [3.99971, 0.53], [4.57971, 0.53]] },
  fuse_hiss: { sheet: "industrial", variants: [[5.15971, 0.59], [5.79971, 0.59], [6.43971, 0.59]] },
  shot_gatling: { sheet: "industrial", variants: [[7.07971, 0.4], [7.52971, 0.39973], [7.97944, 0.39963]] },
  tesla_zap: { sheet: "industrial", variants: [[8.42906, 0.45], [8.92906, 0.45], [9.42906, 0.45]] },
  pw_iron_horse: { sheet: "industrial", variants: [[9.92906, 2.39719], [12.37625, 2.39717]] },
  pw_zeppelin: { sheet: "industrial", variants: [[14.82342, 2.45842], [17.33183, 2.4584]] },
  evolve_fanfare_industrial: { sheet: "industrial", variants: [[19.84023, 2.0]] },
  step_mech: { sheet: "modern", variants: [[0.15, 0.204], [0.404, 0.204], [0.658, 0.204]] },
  shot_rifle: { sheet: "modern", variants: [[0.912, 0.58154], [1.54354, 0.62598], [2.21952, 0.56402]] },
  shot_mg: { sheet: "modern", variants: [[2.83354, 0.16], [3.04354, 0.16], [3.25354, 0.16]] },
  shot_flak: { sheet: "modern", variants: [[3.46354, 0.44354], [3.95708, 0.45658], [4.46367, 0.44462]] },
  radio_call: { sheet: "modern", variants: [[4.95829, 0.56], [5.56829, 0.56]] },
  pw_paratroop: { sheet: "modern", variants: [[6.17829, 1.78996], [8.01825, 1.78996]] },
  pw_bomber: { sheet: "modern", variants: [[9.85821, 2.22817], [12.13637, 2.2236]] },
  shot_rail: { sheet: "future", variants: [[0.15, 0.54], [0.74, 0.54], [1.33, 0.54]] },
  shot_laser: { sheet: "future", variants: [[1.92, 0.16], [2.13, 0.16], [2.34, 0.16]] },
  shot_arc: { sheet: "future", variants: [[2.55, 0.28], [2.88, 0.28], [3.21, 0.28]] },
  shot_plasma: { sheet: "future", variants: [[3.54, 0.28], [3.87, 0.28], [4.2, 0.28]] },
  emp_pulse: { sheet: "future", variants: [[4.53, 0.7], [5.28, 0.7]] },
  time_stop: { sheet: "future", variants: [[6.03, 1.37883], [7.45883, 1.384]] },
  gravity_hum: { sheet: "future", variants: [[8.89283, 0.8], [9.74283, 0.8]] },
  pw_lance: { sheet: "future", variants: [[10.59283, 2.16169], [12.80452, 2.15106]] },
  pw_nanite: { sheet: "future", variants: [[15.00558, 1.39896], [16.45454, 1.39987]] },
  shot_ion: { sheet: "cosmic", variants: [[0.15, 0.36], [0.56, 0.36], [0.97, 0.36]] },
  shot_void: { sheet: "cosmic", variants: [[1.38, 0.38], [1.81, 0.38], [2.24, 0.38]] },
  shot_starburst: { sheet: "cosmic", variants: [[2.67, 0.27], [2.99, 0.27], [3.31, 0.2699]] },
  shot_tachyon: { sheet: "cosmic", variants: [[3.6299, 0.63652], [4.31642, 0.64008], [5.0065, 0.63604]] },
  blink_warp: { sheet: "cosmic", variants: [[5.69254, 0.53], [6.27254, 0.53], [6.85254, 0.53]] },
  drone_launch: { sheet: "cosmic", variants: [[7.43254, 0.6], [8.08254, 0.6], [8.73254, 0.6]] },
  pw_starfall: { sheet: "cosmic", variants: [[9.38254, 2.59479], [12.02733, 2.59735]] },
  pw_warp: { sheet: "cosmic", variants: [[14.67469, 1.86475], [16.58944, 1.86481]] },
  evolve_fanfare_cosmic: { sheet: "cosmic", variants: [[18.50425, 2.0]] },
  cap_thud: { sheet: "capsule", variants: [[0.15, 0.55365], [0.75365, 0.54933], [1.35298, 0.54931]] },
  cap_riser: { sheet: "capsule", variants: [[1.95229, 1.5]] },
  cap_climb_1: { sheet: "capsule", variants: [[3.50229, 0.99096], [4.54325, 0.99287]] },
  cap_climb_2: { sheet: "capsule", variants: [[5.58613, 1.3], [6.93612, 1.3]] },
  cap_climb_3: { sheet: "capsule", variants: [[8.28613, 1.4], [9.73612, 1.4]] },
  cap_climb_4: { sheet: "capsule", variants: [[11.18613, 1.43446], [12.67058, 1.43446]] },
  cap_climb_5: { sheet: "capsule", variants: [[14.15504, 1.91383], [16.11887, 1.87854]] },
  cap_climb_6: { sheet: "capsule", variants: [[18.04742, 2.35681], [20.45423, 2.39827]] },
  cap_summit_rise: { sheet: "capsule", variants: [[22.9025, 0.75], [23.7025, 0.75]] },
  cap_clunk: { sheet: "capsule", variants: [[24.5025, 0.2], [24.7525, 0.2], [25.0025, 0.2]] },
  cap_burst: { sheet: "capsule", variants: [[25.2525, 1.58475]] },
  cap_burst_platinum: { sheet: "capsule", variants: [[26.88725, 3.0]] },
  cap_burst_aeon: { sheet: "capsule", variants: [[29.93725, 3.54981]] },
  card_flip: { sheet: "capsule", variants: [[33.53706, 0.06848], [33.65554, 0.06858], [33.77412, 0.06856]] },
  foil_shine: { sheet: "capsule", variants: [[33.89269, 0.5245], [34.46719, 0.52704]] },
  rarity_common: { sheet: "capsule", variants: [[35.04423, 1.3]] },
  rarity_rare: { sheet: "capsule", variants: [[36.39423, 1.758]] },
  rarity_epic: { sheet: "capsule", variants: [[38.20223, 1.6]] },
  rarity_legendary: { sheet: "capsule", variants: [[39.85223, 2.6]] },
  walkout_bass: { sheet: "capsule", variants: [[42.50223, 1.6]] },
  copy_tick: { sheet: "capsule", variants: [[44.15223, 0.03], [44.23223, 0.03], [44.31223, 0.03]] },
  upgrade_ready: { sheet: "capsule", variants: [[44.39223, 0.7]] },
  upgrade_slam: { sheet: "capsule", variants: [[45.14223, 0.93835], [46.13058, 0.92756]] },
  level_up: { sheet: "capsule", variants: [[47.10815, 1.6]] },
  reel_tick: { sheet: "capsule", variants: [[48.75815, 0.02], [48.82815, 0.02], [48.89815, 0.02]] },
};

export const MUSIC_FILES: Readonly<Record<string, MusicFile>> = {
  "layer.intensity.bronze": { src: "audio/music/layer.intensity.bronze.638ec0e0.ogg", bytes: 48305, seconds: 9.327, loopStart: 0.3, loopLength: 8.727271, alt: "audio/music/layer.intensity.bronze.6773ef5f.m4a" },
  "layer.intensity.cosmic": { src: "audio/music/layer.intensity.cosmic.5a065b8c.ogg", bytes: 48178, seconds: 9.327, loopStart: 0.3, loopLength: 8.727271, alt: "audio/music/layer.intensity.cosmic.3f470959.m4a" },
  "layer.intensity.future": { src: "audio/music/layer.intensity.future.7b1210b4.ogg", bytes: 47885, seconds: 9.327, loopStart: 0.3, loopLength: 8.727271, alt: "audio/music/layer.intensity.future.be51ddb2.m4a" },
  "layer.intensity.gunpowder": { src: "audio/music/layer.intensity.gunpowder.3f2d6355.ogg", bytes: 48179, seconds: 9.327, loopStart: 0.3, loopLength: 8.727271, alt: "audio/music/layer.intensity.gunpowder.f9d1113b.m4a" },
  "layer.intensity.industrial": { src: "audio/music/layer.intensity.industrial.4e94fe12.ogg", bytes: 48175, seconds: 9.327, loopStart: 0.3, loopLength: 8.727271, alt: "audio/music/layer.intensity.industrial.38989ef4.m4a" },
  "layer.intensity.medieval": { src: "audio/music/layer.intensity.medieval.a10679ef.ogg", bytes: 48214, seconds: 9.327, loopStart: 0.3, loopLength: 8.727271, alt: "audio/music/layer.intensity.medieval.b575fae6.m4a" },
  "layer.intensity.modern": { src: "audio/music/layer.intensity.modern.70a27f8b.ogg", bytes: 48097, seconds: 9.327, loopStart: 0.3, loopLength: 8.727271, alt: "audio/music/layer.intensity.modern.66f8948a.m4a" },
  "layer.intensity.stone": { src: "audio/music/layer.intensity.stone.135b6a1f.ogg", bytes: 48216, seconds: 9.327, loopStart: 0.3, loopLength: 8.727271, alt: "audio/music/layer.intensity.stone.3ce3b15a.m4a" },
  "layer.overdrive": { src: "audio/music/layer.overdrive.c12b44d2.ogg", bytes: 47710, seconds: 9.327, loopStart: 0.3, loopLength: 8.727271, alt: "audio/music/layer.overdrive.95c3a4b2.m4a" },
  "layer.siege": { src: "audio/music/layer.siege.695cb3b9.ogg", bytes: 30982, seconds: 9.327, loopStart: 0.3, loopLength: 8.727271, alt: "audio/music/layer.siege.d77a8f5c.m4a" },
  "music.bronze": { src: "audio/music/music.bronze.7a06e807.ogg", bytes: 592282, seconds: 96.6, loopStart: 0.3, loopLength: 96.0, alt: "audio/music/music.bronze.90a9fb91.m4a" },
  "music.capsule": { src: "audio/music/music.capsule.bb040c67.ogg", bytes: 239269, seconds: 39.0, loopStart: 0.3, loopLength: 38.4, alt: "audio/music/music.capsule.15dd0cb3.m4a" },
  "music.cosmic": { src: "audio/music/music.cosmic.89df058d.ogg", bytes: 592110, seconds: 96.6, loopStart: 0.3, loopLength: 96.0, alt: "audio/music/music.cosmic.19e7763a.m4a" },
  "music.future": { src: "audio/music/music.future.a096b02e.ogg", bytes: 592173, seconds: 96.6, loopStart: 0.3, loopLength: 96.0, alt: "audio/music/music.future.d3dbcb69.m4a" },
  "music.gunpowder": { src: "audio/music/music.gunpowder.0f851b08.ogg", bytes: 590747, seconds: 96.6, loopStart: 0.3, loopLength: 96.0, alt: "audio/music/music.gunpowder.e0acfe86.m4a" },
  "music.industrial": { src: "audio/music/music.industrial.3efea8ac.ogg", bytes: 592157, seconds: 96.6, loopStart: 0.3, loopLength: 96.0, alt: "audio/music/music.industrial.6b3433a9.m4a" },
  "music.medieval": { src: "audio/music/music.medieval.128ef7a3.ogg", bytes: 591881, seconds: 96.6, loopStart: 0.3, loopLength: 96.0, alt: "audio/music/music.medieval.a9e99f6a.m4a" },
  "music.menu": { src: "audio/music/music.menu.60d5e193.ogg", bytes: 284406, seconds: 46.314, loopStart: 0.3, loopLength: 45.714292, alt: "audio/music/music.menu.9083ec5a.m4a" },
  "music.modern": { src: "audio/music/music.modern.b0f3db53.ogg", bytes: 592322, seconds: 96.6, loopStart: 0.3, loopLength: 96.0, alt: "audio/music/music.modern.456c2b7e.m4a" },
  "music.stone": { src: "audio/music/music.stone.12b23faa.ogg", bytes: 592209, seconds: 96.6, loopStart: 0.3, loopLength: 96.0, alt: "audio/music/music.stone.c610e17b.m4a" },
  "stinger.defeat": { src: "audio/music/stinger.defeat.5ae50cdd.ogg", bytes: 82136, seconds: 11.5, alt: "audio/music/stinger.defeat.c30f123c.m4a" },
  "stinger.defeat.k2": { src: "audio/music/stinger.defeat.k2.bd3fcc62.ogg", bytes: 81971, seconds: 11.5, alt: "audio/music/stinger.defeat.k2.3c1e77b9.m4a" },
  "stinger.defeat.k4": { src: "audio/music/stinger.defeat.k4.271ecd2e.ogg", bytes: 81823, seconds: 11.5, alt: "audio/music/stinger.defeat.k4.91e4d56e.m4a" },
  "stinger.defeat.k5": { src: "audio/music/stinger.defeat.k5.0a0753c9.ogg", bytes: 81972, seconds: 11.5, alt: "audio/music/stinger.defeat.k5.f6a42d51.m4a" },
  "stinger.defeat.k6": { src: "audio/music/stinger.defeat.k6.7afaf999.ogg", bytes: 82181, seconds: 11.494, alt: "audio/music/stinger.defeat.k6.47668bb0.m4a" },
  "stinger.defeat.k7": { src: "audio/music/stinger.defeat.k7.592c23f8.ogg", bytes: 81974, seconds: 11.5, alt: "audio/music/stinger.defeat.k7.ff4bc7ab.m4a" },
  "stinger.defeat.k8": { src: "audio/music/stinger.defeat.k8.73d05c2a.ogg", bytes: 81961, seconds: 11.5, alt: "audio/music/stinger.defeat.k8.4bb67b44.m4a" },
  "stinger.defeat.k9": { src: "audio/music/stinger.defeat.k9.23aa99ee.ogg", bytes: 82167, seconds: 11.492, alt: "audio/music/stinger.defeat.k9.e6f69824.m4a" },
  "stinger.victory": { src: "audio/music/stinger.victory.1cdbc845.ogg", bytes: 44228, seconds: 6.16, alt: "audio/music/stinger.victory.4c860694.m4a" },
  "stinger.victory.k2": { src: "audio/music/stinger.victory.k2.242c2f25.ogg", bytes: 43945, seconds: 6.133, alt: "audio/music/stinger.victory.k2.8a165e56.m4a" },
  "stinger.victory.k4": { src: "audio/music/stinger.victory.k4.43e8d868.ogg", bytes: 44234, seconds: 6.166, alt: "audio/music/stinger.victory.k4.701ceb85.m4a" },
  "stinger.victory.k5": { src: "audio/music/stinger.victory.k5.9c6692d0.ogg", bytes: 43517, seconds: 6.07, alt: "audio/music/stinger.victory.k5.0e4d2f9c.m4a" },
  "stinger.victory.k6": { src: "audio/music/stinger.victory.k6.3d2ab8c0.ogg", bytes: 43670, seconds: 6.088, alt: "audio/music/stinger.victory.k6.9b279902.m4a" },
  "stinger.victory.k7": { src: "audio/music/stinger.victory.k7.06731f07.ogg", bytes: 43675, seconds: 6.094, alt: "audio/music/stinger.victory.k7.2cc927a6.m4a" },
  "stinger.victory.k8": { src: "audio/music/stinger.victory.k8.53e2c421.ogg", bytes: 43666, seconds: 6.101, alt: "audio/music/stinger.victory.k8.81d703da.m4a" },
  "stinger.victory.k9": { src: "audio/music/stinger.victory.k9.b6e0f831.ogg", bytes: 44261, seconds: 6.175, alt: "audio/music/stinger.victory.k9.f68b54ae.m4a" },
};
