/**
 * Generated by `tools/audio/build.py` from the renders in `tools/audio`. Do not edit by hand:
 * change the sound design or the arrangements there and rebuild (see tools/audio/README.md).
 *
 * - `SFX_SHEETS`: one Ogg Opus sprite sheet per sound group, paths relative to the site base.
 * - `SFX_FILES`: per sound id, its sheet and each variant's [offset, duration] in seconds.
 * - `MUSIC_FILES`: per music cue, stinger and layer stem, the file and, for loops, the loop
 *   window (`loopStart`, `loopLength` in seconds; any window of that length inside the file
 *   loops seamlessly).
 */

export interface SfxSheetFile {
  src: string;
  bytes: number;
  seconds: number;
}

export interface SfxFileEntry {
  sheet: string;
  /** [offset, duration] in seconds per variant. */
  variants: readonly (readonly [number, number])[];
}

export interface MusicFile {
  src: string;
  bytes: number;
  seconds: number;
  loopStart?: number;
  loopLength?: number;
}

export const SFX_BYTES = 960789;
export const MUSIC_BYTES = 2857698;

export const SFX_SHEETS: Readonly<Record<string, SfxSheetFile>> = {
  ui: { src: "audio/sfx/ui.a64cba6c.ogg", bytes: 16792, seconds: 3.761 },
  battle: { src: "audio/sfx/battle.310a1b39.ogg", bytes: 167201, seconds: 33.453 },
  stone: { src: "audio/sfx/stone.fe5b063f.ogg", bytes: 77834, seconds: 15.618 },
  medieval: { src: "audio/sfx/medieval.144c3fd6.ogg", bytes: 51988, seconds: 10.19 },
  match: { src: "audio/sfx/match.5bb69d5b.ogg", bytes: 226069, seconds: 44.318 },
  gunpowder: { src: "audio/sfx/gunpowder.a54a205a.ogg", bytes: 109562, seconds: 21.508 },
  modern: { src: "audio/sfx/modern.41347b2a.ogg", bytes: 67622, seconds: 13.383 },
  future: { src: "audio/sfx/future.f7d75b04.ogg", bytes: 89846, seconds: 17.822 },
  capsule: { src: "audio/sfx/capsule.7a3c0393.ogg", bytes: 153875, seconds: 30.821 },
};

export const SFX_FILES: Readonly<Record<string, SfxFileEntry>> = {
  ui_click: { sheet: "ui", variants: [[0.05, 0.035], [0.135, 0.035], [0.22, 0.035]] },
  ui_hover: { sheet: "ui", variants: [[0.305, 0.025], [0.38, 0.025], [0.455, 0.025]] },
  ui_deny: { sheet: "ui", variants: [[0.53, 0.24], [0.82, 0.24], [1.11, 0.24]] },
  ui_toggle: { sheet: "ui", variants: [[1.4, 0.075], [1.525, 0.075], [1.65, 0.075]] },
  ui_tab: { sheet: "ui", variants: [[1.775, 0.09688], [1.92188, 0.09433], [2.06621, 0.09467]] },
  ui_confirm: { sheet: "ui", variants: [[2.21088, 0.47], [2.73088, 0.47]] },
  meter_pip: { sheet: "ui", variants: [[3.25088, 0.12], [3.42088, 0.12], [3.59088, 0.12]] },
  spawn_pop: { sheet: "battle", variants: [[0.05, 0.12], [0.22, 0.12], [0.39, 0.12]] },
  spawn_heavy: { sheet: "battle", variants: [[0.56, 0.39925], [1.00925, 0.43502], [1.49427, 0.42212]] },
  step_heavy: { sheet: "battle", variants: [[1.9664, 0.14], [2.1564, 0.14], [2.3464, 0.14]] },
  swing_whoosh: { sheet: "battle", variants: [[2.5364, 0.1659], [2.75229, 0.16723], [2.96952, 0.16485]] },
  hit_blunt: { sheet: "battle", variants: [[3.18438, 0.12], [3.35438, 0.12], [3.52438, 0.12]] },
  hit_slash: { sheet: "battle", variants: [[3.69437, 0.12], [3.86437, 0.12], [4.03437, 0.12]] },
  hit_pierce: { sheet: "battle", variants: [[4.20437, 0.08], [4.33437, 0.08], [4.46438, 0.08]] },
  hit_bullet: { sheet: "battle", variants: [[4.59438, 0.125], [4.76938, 0.10148], [4.92085, 0.18]] },
  hit_laser: { sheet: "battle", variants: [[5.15085, 0.12], [5.32085, 0.12], [5.49085, 0.12]] },
  hit_heavy: { sheet: "battle", variants: [[5.66085, 0.33831], [6.04917, 0.34396], [6.44313, 0.33456]] },
  hit_effective: { sheet: "battle", variants: [[6.82769, 0.304], [7.18169, 0.304], [7.53569, 0.304]] },
  explosion_s: { sheet: "battle", variants: [[7.88969, 0.396], [8.33569, 0.4276], [8.81329, 0.38688]] },
  explosion_m: { sheet: "battle", variants: [[9.25017, 0.97033], [10.2705, 0.96323], [11.28373, 0.96779]] },
  die_bio: { sheet: "battle", variants: [[12.30152, 0.35], [12.70152, 0.35], [13.10152, 0.35]] },
  die_mech: { sheet: "battle", variants: [[13.50152, 0.43515], [13.98667, 0.44121], [14.47787, 0.44019]] },
  prop_drop: { sheet: "battle", variants: [[14.96806, 0.233], [15.25106, 0.233], [15.53406, 0.233]] },
  heal_tick: { sheet: "battle", variants: [[15.81706, 0.35], [16.21706, 0.35], [16.61706, 0.35]] },
  shield_up: { sheet: "battle", variants: [[17.01706, 0.6], [17.66706, 0.6], [18.31706, 0.6]] },
  turret_build: { sheet: "battle", variants: [[18.96706, 0.8], [19.81706, 0.8], [20.66706, 0.8]] },
  turret_sell: { sheet: "battle", variants: [[21.51706, 0.58], [22.14706, 0.58], [22.77706, 0.58]] },
  turret_upgrade: { sheet: "battle", variants: [[23.40706, 0.68542], [24.14248, 0.68708]] },
  slot_buy: { sheet: "battle", variants: [[24.87956, 0.45], [25.37956, 0.45]] },
  base_hit: { sheet: "battle", variants: [[25.87956, 0.49617], [26.42573, 0.50004], [26.97577, 0.4936]] },
  coin_gain: { sheet: "battle", variants: [[27.51938, 0.295], [27.86437, 0.295], [28.20938, 0.295]] },
  xp_tick: { sheet: "battle", variants: [[28.55438, 0.07], [28.67438, 0.07], [28.79437, 0.07]] },
  evolve_ready: { sheet: "battle", variants: [[28.91437, 1.22865]] },
  power_ready: { sheet: "battle", variants: [[30.19302, 0.77958]] },
  power_telegraph: { sheet: "battle", variants: [[31.0226, 1.0], [32.0726, 1.0]] },
  emote_pop: { sheet: "battle", variants: [[33.1226, 0.06], [33.2326, 0.06], [33.3426, 0.06]] },
  shot_sling: { sheet: "stone", variants: [[0.05, 0.13], [0.23, 0.13], [0.41, 0.13]] },
  shot_catapult: { sheet: "stone", variants: [[0.59, 0.48752], [1.12752, 0.49871], [1.67623, 0.48285]] },
  bee_buzz: { sheet: "stone", variants: [[2.20908, 0.4], [2.65908, 0.4], [3.10908, 0.4]] },
  log_roll: { sheet: "stone", variants: [[3.55908, 0.69969], [4.30877, 0.6995], [5.05827, 0.69965]] },
  toad_tongue: { sheet: "stone", variants: [[5.80792, 0.22], [6.07792, 0.22], [6.34792, 0.22]] },
  pw_stampede: { sheet: "stone", variants: [[6.61792, 2.0], [8.66792, 2.0]] },
  pw_meteor: { sheet: "stone", variants: [[10.71792, 2.4], [13.16792, 2.4]] },
  shot_bow: { sheet: "medieval", variants: [[0.05, 0.25], [0.35, 0.25], [0.65, 0.25]] },
  shot_crossbow: { sheet: "medieval", variants: [[0.95, 0.256], [1.256, 0.256], [1.562, 0.256]] },
  cauldron_pour: { sheet: "medieval", variants: [[1.868, 0.8], [2.718, 0.8], [3.568, 0.8]] },
  goose_honk: { sheet: "medieval", variants: [[4.418, 0.22], [4.688, 0.22], [4.958, 0.22]] },
  pw_arrows: { sheet: "medieval", variants: [[5.228, 1.4909], [6.7689, 1.52092]] },
  pw_decree: { sheet: "medieval", variants: [[8.33981, 1.8]] },
  spawn_legendary: { sheet: "match", variants: [[0.05, 1.8], [1.9, 1.8]] },
  explosion_l: { sheet: "match", variants: [[3.75, 1.68948], [5.48948, 1.68431], [7.22379, 1.67835]] },
  base_crumble: { sheet: "match", variants: [[8.95215, 1.3249], [10.32704, 1.339]] },
  base_destroyed: { sheet: "match", variants: [[11.71604, 2.85]] },
  treasury_up: { sheet: "match", variants: [[14.61604, 0.75], [15.41604, 0.75]] },
  evolve_riser: { sheet: "match", variants: [[16.21604, 2.5]] },
  evolve_fanfare_stone: { sheet: "match", variants: [[18.76604, 1.97567]] },
  evolve_fanfare_medieval: { sheet: "match", variants: [[20.79171, 2.0]] },
  evolve_fanfare_gunpowder: { sheet: "match", variants: [[22.84171, 2.0]] },
  evolve_fanfare_modern: { sheet: "match", variants: [[24.89171, 2.0]] },
  evolve_fanfare_future: { sheet: "match", variants: [[26.94171, 2.0]] },
  evolve_enemy: { sheet: "match", variants: [[28.99171, 1.6]] },
  last_stand_armed: { sheet: "match", variants: [[30.64171, 1.4]] },
  last_stand_charge: { sheet: "match", variants: [[32.09171, 1.0]] },
  last_stand_fire: { sheet: "match", variants: [[33.14171, 1.29935]] },
  overdrive_horn: { sheet: "match", variants: [[34.49106, 1.44898]] },
  siege_bell: { sheet: "match", variants: [[35.99004, 3.4]] },
  victory_jingle: { sheet: "match", variants: [[39.44004, 2.17754]] },
  defeat_jingle: { sheet: "match", variants: [[41.66758, 2.6]] },
  shot_musket: { sheet: "gunpowder", variants: [[0.05, 0.72617], [0.82617, 0.7261], [1.60227, 0.72619]] },
  shot_lob: { sheet: "gunpowder", variants: [[2.37846, 0.25], [2.67846, 0.25], [2.97846, 0.25]] },
  shot_cannon: { sheet: "gunpowder", variants: [[3.27846, 1.42706], [4.75552, 1.42542], [6.23094, 1.42533]] },
  shot_grapeshot: { sheet: "gunpowder", variants: [[7.70627, 0.74215], [8.49842, 0.74175], [9.29017, 0.74162]] },
  shot_rocket: { sheet: "gunpowder", variants: [[10.08179, 0.56], [10.69179, 0.56], [11.30179, 0.56]] },
  bomb_whistle: { sheet: "gunpowder", variants: [[11.91179, 0.7], [12.66179, 0.7]] },
  pw_smoke: { sheet: "gunpowder", variants: [[13.41179, 1.75], [15.21179, 1.75]] },
  pw_broadside: { sheet: "gunpowder", variants: [[17.01179, 2.2], [19.26179, 2.19575]] },
  step_mech: { sheet: "modern", variants: [[0.05, 0.204], [0.304, 0.204], [0.558, 0.204]] },
  shot_rifle: { sheet: "modern", variants: [[0.812, 0.43306], [1.29506, 0.4185], [1.76356, 0.40119]] },
  shot_mg: { sheet: "modern", variants: [[2.21475, 0.143], [2.40775, 0.143], [2.60075, 0.143]] },
  shot_flak: { sheet: "modern", variants: [[2.79375, 0.45619], [3.29994, 0.435], [3.78494, 0.44327]] },
  radio_call: { sheet: "modern", variants: [[4.27821, 0.56], [4.88821, 0.56]] },
  pw_paratroop: { sheet: "modern", variants: [[5.49821, 1.79169], [7.3399, 1.79133]] },
  pw_bomber: { sheet: "modern", variants: [[9.18123, 2.05858], [11.28981, 2.04304]] },
  shot_rail: { sheet: "future", variants: [[0.05, 0.54], [0.64, 0.54], [1.23, 0.54]] },
  shot_laser: { sheet: "future", variants: [[1.82, 0.16], [2.03, 0.16], [2.24, 0.16]] },
  shot_arc: { sheet: "future", variants: [[2.45, 0.28], [2.78, 0.28], [3.11, 0.28]] },
  shot_plasma: { sheet: "future", variants: [[3.44, 0.28], [3.77, 0.28], [4.1, 0.28]] },
  emp_pulse: { sheet: "future", variants: [[4.43, 0.7], [5.18, 0.7]] },
  time_stop: { sheet: "future", variants: [[5.93, 1.37883], [7.35883, 1.384]] },
  gravity_hum: { sheet: "future", variants: [[8.79283, 0.8], [9.64283, 0.8]] },
  pw_lance: { sheet: "future", variants: [[10.49283, 2.1739], [12.71673, 2.15648]] },
  pw_nanite: { sheet: "future", variants: [[14.92321, 1.39896], [16.37217, 1.39987]] },
  cap_thud: { sheet: "capsule", variants: [[0.05, 0.38823], [0.48823, 0.38515], [0.92337, 0.39521]] },
  cap_riser: { sheet: "capsule", variants: [[1.36858, 1.5]] },
  cap_climb_1: { sheet: "capsule", variants: [[2.91858, 0.8449], [3.81348, 0.85919]] },
  cap_climb_2: { sheet: "capsule", variants: [[4.72267, 1.3], [6.07267, 1.3]] },
  cap_climb_3: { sheet: "capsule", variants: [[7.42267, 1.4], [8.87267, 1.4]] },
  cap_climb_4: { sheet: "capsule", variants: [[10.32267, 1.43435], [11.80702, 1.43435]] },
  cap_clunk: { sheet: "capsule", variants: [[13.29138, 0.12], [13.46138, 0.12], [13.63138, 0.12]] },
  cap_burst: { sheet: "capsule", variants: [[13.80138, 1.54087]] },
  card_flip: { sheet: "capsule", variants: [[15.39225, 0.06848], [15.51073, 0.06858], [15.62931, 0.06856]] },
  foil_shine: { sheet: "capsule", variants: [[15.74788, 0.5245], [16.32238, 0.52704]] },
  rarity_common: { sheet: "capsule", variants: [[16.89942, 1.3]] },
  rarity_rare: { sheet: "capsule", variants: [[18.24942, 1.758]] },
  rarity_epic: { sheet: "capsule", variants: [[20.05742, 1.6]] },
  rarity_legendary: { sheet: "capsule", variants: [[21.70742, 2.6]] },
  walkout_bass: { sheet: "capsule", variants: [[24.35742, 1.6]] },
  copy_tick: { sheet: "capsule", variants: [[26.00742, 0.03], [26.08742, 0.03], [26.16742, 0.03]] },
  upgrade_ready: { sheet: "capsule", variants: [[26.24742, 0.7]] },
  upgrade_slam: { sheet: "capsule", variants: [[26.99742, 0.93629], [27.98371, 0.9276]] },
  level_up: { sheet: "capsule", variants: [[28.96131, 1.6]] },
  reel_tick: { sheet: "capsule", variants: [[30.61131, 0.02], [30.68131, 0.02], [30.75131, 0.02]] },
};

export const MUSIC_FILES: Readonly<Record<string, MusicFile>> = {
  "layer.intensity.future": { src: "audio/music/layer.intensity.future.b1eb17b5.ogg", bytes: 48186, seconds: 9.327, loopStart: 0.3, loopLength: 8.727271 },
  "layer.intensity.gunpowder": { src: "audio/music/layer.intensity.gunpowder.82274d21.ogg", bytes: 48034, seconds: 9.327, loopStart: 0.3, loopLength: 8.727271 },
  "layer.intensity.medieval": { src: "audio/music/layer.intensity.medieval.3ab004b8.ogg", bytes: 47594, seconds: 9.327, loopStart: 0.3, loopLength: 8.727271 },
  "layer.intensity.modern": { src: "audio/music/layer.intensity.modern.8528c740.ogg", bytes: 48051, seconds: 9.327, loopStart: 0.3, loopLength: 8.727271 },
  "layer.intensity.stone": { src: "audio/music/layer.intensity.stone.3879f855.ogg", bytes: 48001, seconds: 9.327, loopStart: 0.3, loopLength: 8.727271 },
  "layer.overdrive": { src: "audio/music/layer.overdrive.edc32b72.ogg", bytes: 48123, seconds: 9.327, loopStart: 0.3, loopLength: 8.727271 },
  "layer.siege": { src: "audio/music/layer.siege.695cb3b9.ogg", bytes: 30982, seconds: 9.327, loopStart: 0.3, loopLength: 8.727271 },
  "music.capsule": { src: "audio/music/music.capsule.4e701379.ogg", bytes: 239267, seconds: 39.0, loopStart: 0.3, loopLength: 38.4 },
  "music.future": { src: "audio/music/music.future.9ca4a11e.ogg", bytes: 377850, seconds: 52.964, loopStart: 0.3, loopLength: 52.363646 },
  "music.gunpowder": { src: "audio/music/music.gunpowder.382e9669.ogg", bytes: 377732, seconds: 52.964, loopStart: 0.3, loopLength: 52.363646 },
  "music.medieval": { src: "audio/music/music.medieval.d18f72ad.ogg", bytes: 377767, seconds: 52.964, loopStart: 0.3, loopLength: 52.363646 },
  "music.menu": { src: "audio/music/music.menu.284ee7f7.ogg", bytes: 284345, seconds: 46.314, loopStart: 0.3, loopLength: 45.714292 },
  "music.modern": { src: "audio/music/music.modern.a403da45.ogg", bytes: 377773, seconds: 52.964, loopStart: 0.3, loopLength: 52.363646 },
  "music.stone": { src: "audio/music/music.stone.384c443e.ogg", bytes: 377768, seconds: 52.964, loopStart: 0.3, loopLength: 52.363646 },
  "stinger.defeat": { src: "audio/music/stinger.defeat.4444dfc0.ogg", bytes: 82135, seconds: 11.5 },
  "stinger.victory": { src: "audio/music/stinger.victory.d63be094.ogg", bytes: 44090, seconds: 6.156 },
};
