/**
 * The cosmetic collections (DESIGN A18.9.4, owner direction 2026-09-28): emotes, quotes, base flags,
 * national flags, base skins, base decorations and battle backdrops (2026-09-30). Data only: id, collection, rarity, source and the
 * art id (`cosmetic.<collection>.<id>`, A14.4) that the visuals draw.
 *
 * - All earned (A6.2: nothing is sold): starters, the Time Capsule and Wardrobe Crate drop pools
 *   (odds disclosed, see `drops` in `../cosmetics.ts`), Trophy Road nodes, hidden feats; `capsule`
 *   and `crate` items can also be crafted with Dust.
 * - Quotes are fixed, friendly lines (A16.28: no taunts). There is no free text chat anywhere.
 * - National flags are country flags only, drawn in our own style; no political or hate symbols.
 *   A player's flag is only ever their own pick, never inferred from location.
 * - Cosmetics never change numbers, hitboxes or readability (A11 team colour and silhouette rules).
 */
import type { CosmeticItemDef } from '../types';

export const collectionItems: CosmeticItemDef[] = [
  // Emotes: 24 collected emotes, two per age and eight general ones (the 6 starter emotes stay in `emotes`)
  { id: 'bonk', collection: 'emote', rarity: 'rare', source: { kind: 'feat', feat: 'stone_cold' }, art: 'cosmetic.emote.bonk', nameKey: 'cosmetic.emote.bonk.name', theme: 'stone' },
  { id: 'mammoth_toot', collection: 'emote', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.emote.mammoth_toot', nameKey: 'cosmetic.emote.mammoth_toot.name', theme: 'stone' },
  { id: 'laurel_crown', collection: 'emote', rarity: 'rare', source: { kind: 'capsule' }, art: 'cosmetic.emote.laurel_crown', nameKey: 'cosmetic.emote.laurel_crown.name', theme: 'bronze' },
  { id: 'amphora_cheers', collection: 'emote', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.emote.amphora_cheers', nameKey: 'cosmetic.emote.amphora_cheers.name', theme: 'bronze' },
  { id: 'royal_bow', collection: 'emote', rarity: 'rare', source: { kind: 'crate' }, art: 'cosmetic.emote.royal_bow', nameKey: 'cosmetic.emote.royal_bow.name', theme: 'medieval' },
  { id: 'lute_strum', collection: 'emote', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.emote.lute_strum', nameKey: 'cosmetic.emote.lute_strum.name', theme: 'medieval' },
  { id: 'hat_tip', collection: 'emote', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.emote.hat_tip', nameKey: 'cosmetic.emote.hat_tip.name', theme: 'gunpowder' },
  { id: 'cannon_confetti', collection: 'emote', rarity: 'epic', source: { kind: 'crate' }, art: 'cosmetic.emote.cannon_confetti', nameKey: 'cosmetic.emote.cannon_confetti.name', theme: 'gunpowder' },
  { id: 'steam_whistle', collection: 'emote', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.emote.steam_whistle', nameKey: 'cosmetic.emote.steam_whistle.name', theme: 'industrial' },
  { id: 'gear_heart', collection: 'emote', rarity: 'rare', source: { kind: 'road', trophies: 1100 }, art: 'cosmetic.emote.gear_heart', nameKey: 'cosmetic.emote.gear_heart.name', theme: 'industrial' },
  { id: 'radio_roger', collection: 'emote', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.emote.radio_roger', nameKey: 'cosmetic.emote.radio_roger.name', theme: 'modern' },
  { id: 'medal_shine', collection: 'emote', rarity: 'rare', source: { kind: 'capsule' }, art: 'cosmetic.emote.medal_shine', nameKey: 'cosmetic.emote.medal_shine.name', theme: 'modern' },
  { id: 'robo_dance', collection: 'emote', rarity: 'epic', source: { kind: 'crate' }, art: 'cosmetic.emote.robo_dance', nameKey: 'cosmetic.emote.robo_dance.name', theme: 'future' },
  { id: 'holo_wave', collection: 'emote', rarity: 'rare', source: { kind: 'capsule' }, art: 'cosmetic.emote.holo_wave', nameKey: 'cosmetic.emote.holo_wave.name', theme: 'future' },
  { id: 'supernova', collection: 'emote', rarity: 'legendary', source: { kind: 'feat', feat: 'lightspeed' }, art: 'cosmetic.emote.supernova', nameKey: 'cosmetic.emote.supernova.name', theme: 'cosmic' },
  { id: 'orbit_heart', collection: 'emote', rarity: 'epic', source: { kind: 'capsule' }, art: 'cosmetic.emote.orbit_heart', nameKey: 'cosmetic.emote.orbit_heart.name', theme: 'cosmic' },
  { id: 'clap', collection: 'emote', rarity: 'common', source: { kind: 'road', trophies: 250 }, art: 'cosmetic.emote.clap', nameKey: 'cosmetic.emote.clap.name', theme: 'general' },
  { id: 'heart', collection: 'emote', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.emote.heart', nameKey: 'cosmetic.emote.heart.name', theme: 'general' },
  { id: 'wow', collection: 'emote', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.emote.wow', nameKey: 'cosmetic.emote.wow.name', theme: 'general' },
  { id: 'thinking', collection: 'emote', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.emote.thinking', nameKey: 'cosmetic.emote.thinking.name', theme: 'general' },
  { id: 'sleepy', collection: 'emote', rarity: 'rare', source: { kind: 'capsule' }, art: 'cosmetic.emote.sleepy', nameKey: 'cosmetic.emote.sleepy.name', theme: 'general' },
  { id: 'party', collection: 'emote', rarity: 'epic', source: { kind: 'road', trophies: 2400 }, art: 'cosmetic.emote.party', nameKey: 'cosmetic.emote.party.name', theme: 'general' },
  { id: 'cool_shades', collection: 'emote', rarity: 'rare', source: { kind: 'crate' }, art: 'cosmetic.emote.cool_shades', nameKey: 'cosmetic.emote.cool_shades.name', theme: 'general' },
  { id: 'oops', collection: 'emote', rarity: 'common', source: { kind: 'road', trophies: 600 }, art: 'cosmetic.emote.oops', nameKey: 'cosmetic.emote.oops.name', theme: 'general' },
  // Quotes: 40 fixed, friendly one-liners (A16.28: no taunts); 4 starters
  { id: 'glhf', collection: 'quote', rarity: 'common', source: { kind: 'start' }, art: 'cosmetic.quote.glhf', nameKey: 'cosmetic.quote.glhf.name', textKey: 'cosmetic.quote.glhf.text' },
  { id: 'well_played', collection: 'quote', rarity: 'common', source: { kind: 'start' }, art: 'cosmetic.quote.well_played', nameKey: 'cosmetic.quote.well_played.name', textKey: 'cosmetic.quote.well_played.text' },
  { id: 'nice_move', collection: 'quote', rarity: 'common', source: { kind: 'start' }, art: 'cosmetic.quote.nice_move', nameKey: 'cosmetic.quote.nice_move.name', textKey: 'cosmetic.quote.nice_move.text' },
  { id: 'so_close', collection: 'quote', rarity: 'common', source: { kind: 'start' }, art: 'cosmetic.quote.so_close', nameKey: 'cosmetic.quote.so_close.name', textKey: 'cosmetic.quote.so_close.text' },
  { id: 'rematch', collection: 'quote', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.quote.rematch', nameKey: 'cosmetic.quote.rematch.name', textKey: 'cosmetic.quote.rematch.text' },
  { id: 'respect', collection: 'quote', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.quote.respect', nameKey: 'cosmetic.quote.respect.name', textKey: 'cosmetic.quote.respect.text' },
  { id: 'history', collection: 'quote', rarity: 'rare', source: { kind: 'capsule' }, art: 'cosmetic.quote.history', nameKey: 'cosmetic.quote.history.name', textKey: 'cosmetic.quote.history.text' },
  { id: 'mammoth_mood', collection: 'quote', rarity: 'rare', source: { kind: 'capsule' }, art: 'cosmetic.quote.mammoth_mood', nameKey: 'cosmetic.quote.mammoth_mood.name', textKey: 'cosmetic.quote.mammoth_mood.text' },
  { id: 'back_in_my_age', collection: 'quote', rarity: 'rare', source: { kind: 'crate' }, art: 'cosmetic.quote.back_in_my_age', nameKey: 'cosmetic.quote.back_in_my_age.name', textKey: 'cosmetic.quote.back_in_my_age.text' },
  { id: 'fire_invention', collection: 'quote', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.quote.fire_invention', nameKey: 'cosmetic.quote.fire_invention.name', textKey: 'cosmetic.quote.fire_invention.text' },
  { id: 'clubs_style', collection: 'quote', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.quote.clubs_style', nameKey: 'cosmetic.quote.clubs_style.name', textKey: 'cosmetic.quote.clubs_style.text' },
  { id: 'wheel', collection: 'quote', rarity: 'rare', source: { kind: 'capsule' }, art: 'cosmetic.quote.wheel', nameKey: 'cosmetic.quote.wheel.name', textKey: 'cosmetic.quote.wheel.text' },
  { id: 'shiny', collection: 'quote', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.quote.shiny', nameKey: 'cosmetic.quote.shiny.name', textKey: 'cosmetic.quote.shiny.text' },
  { id: 'moat', collection: 'quote', rarity: 'rare', source: { kind: 'capsule' }, art: 'cosmetic.quote.moat', nameKey: 'cosmetic.quote.moat.name', textKey: 'cosmetic.quote.moat.text' },
  { id: 'knightly', collection: 'quote', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.quote.knightly', nameKey: 'cosmetic.quote.knightly.name', textKey: 'cosmetic.quote.knightly.text' },
  { id: 'fashionably_late', collection: 'quote', rarity: 'rare', source: { kind: 'capsule' }, art: 'cosmetic.quote.fashionably_late', nameKey: 'cosmetic.quote.fashionably_late.name', textKey: 'cosmetic.quote.fashionably_late.text' },
  { id: 'powder_dry', collection: 'quote', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.quote.powder_dry', nameKey: 'cosmetic.quote.powder_dry.name', textKey: 'cosmetic.quote.powder_dry.text' },
  { id: 'full_steam', collection: 'quote', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.quote.full_steam', nameKey: 'cosmetic.quote.full_steam.name', textKey: 'cosmetic.quote.full_steam.text' },
  { id: 'tea_break', collection: 'quote', rarity: 'rare', source: { kind: 'crate' }, art: 'cosmetic.quote.tea_break', nameKey: 'cosmetic.quote.tea_break.name', textKey: 'cosmetic.quote.tea_break.text' },
  { id: 'over_and_out', collection: 'quote', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.quote.over_and_out', nameKey: 'cosmetic.quote.over_and_out.name', textKey: 'cosmetic.quote.over_and_out.text' },
  { id: 'upgrade_complete', collection: 'quote', rarity: 'rare', source: { kind: 'capsule' }, art: 'cosmetic.quote.upgrade_complete', nameKey: 'cosmetic.quote.upgrade_complete.name', textKey: 'cosmetic.quote.upgrade_complete.text' },
  { id: 'beep_boop', collection: 'quote', rarity: 'epic', source: { kind: 'crate' }, art: 'cosmetic.quote.beep_boop', nameKey: 'cosmetic.quote.beep_boop.name', textKey: 'cosmetic.quote.beep_boop.text' },
  { id: 'to_the_stars', collection: 'quote', rarity: 'epic', source: { kind: 'capsule' }, art: 'cosmetic.quote.to_the_stars', nameKey: 'cosmetic.quote.to_the_stars.name', textKey: 'cosmetic.quote.to_the_stars.text' },
  { id: 'time_flies', collection: 'quote', rarity: 'rare', source: { kind: 'road', trophies: 1500 }, art: 'cosmetic.quote.time_flies', nameKey: 'cosmetic.quote.time_flies.name', textKey: 'cosmetic.quote.time_flies.text' },
  { id: 'plot_twist', collection: 'quote', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.quote.plot_twist', nameKey: 'cosmetic.quote.plot_twist.name', textKey: 'cosmetic.quote.plot_twist.text' },
  { id: 'did_not_see', collection: 'quote', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.quote.did_not_see', nameKey: 'cosmetic.quote.did_not_see.name', textKey: 'cosmetic.quote.did_not_see.text' },
  { id: 'bold_strategy', collection: 'quote', rarity: 'rare', source: { kind: 'capsule' }, art: 'cosmetic.quote.bold_strategy', nameKey: 'cosmetic.quote.bold_strategy.name', textKey: 'cosmetic.quote.bold_strategy.text' },
  { id: 'oops_mine', collection: 'quote', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.quote.oops_mine', nameKey: 'cosmetic.quote.oops_mine.name', textKey: 'cosmetic.quote.oops_mine.text' },
  { id: 'thinking', collection: 'quote', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.quote.thinking', nameKey: 'cosmetic.quote.thinking.name', textKey: 'cosmetic.quote.thinking.text' },
  { id: 'one_more_wave', collection: 'quote', rarity: 'common', source: { kind: 'road', trophies: 900 }, art: 'cosmetic.quote.one_more_wave', nameKey: 'cosmetic.quote.one_more_wave.name', textKey: 'cosmetic.quote.one_more_wave.text' },
  { id: 'epic_battle', collection: 'quote', rarity: 'epic', source: { kind: 'capsule' }, art: 'cosmetic.quote.epic_battle', nameKey: 'cosmetic.quote.epic_battle.name', textKey: 'cosmetic.quote.epic_battle.text' },
  { id: 'hold_the_line', collection: 'quote', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.quote.hold_the_line', nameKey: 'cosmetic.quote.hold_the_line.name', textKey: 'cosmetic.quote.hold_the_line.text' },
  { id: 'charge', collection: 'quote', rarity: 'common', source: { kind: 'road', trophies: 450 }, art: 'cosmetic.quote.charge', nameKey: 'cosmetic.quote.charge.name', textKey: 'cosmetic.quote.charge.text' },
  { id: 'snack_break', collection: 'quote', rarity: 'rare', source: { kind: 'capsule' }, art: 'cosmetic.quote.snack_break', nameKey: 'cosmetic.quote.snack_break.name', textKey: 'cosmetic.quote.snack_break.text' },
  { id: 'nice_flag', collection: 'quote', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.quote.nice_flag', nameKey: 'cosmetic.quote.nice_flag.name', textKey: 'cosmetic.quote.nice_flag.text' },
  { id: 'next_age', collection: 'quote', rarity: 'rare', source: { kind: 'capsule' }, art: 'cosmetic.quote.next_age', nameKey: 'cosmetic.quote.next_age.name', textKey: 'cosmetic.quote.next_age.text' },
  { id: 'comeback', collection: 'quote', rarity: 'epic', source: { kind: 'feat', feat: 'back_from_the_brink' }, art: 'cosmetic.quote.comeback', nameKey: 'cosmetic.quote.comeback.name', textKey: 'cosmetic.quote.comeback.text' },
  { id: 'gg_wp', collection: 'quote', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.quote.gg_wp', nameKey: 'cosmetic.quote.gg_wp.name', textKey: 'cosmetic.quote.gg_wp.text' },
  { id: 'honour', collection: 'quote', rarity: 'legendary', source: { kind: 'feat', feat: 'underdog' }, art: 'cosmetic.quote.honour', nameKey: 'cosmetic.quote.honour.name', textKey: 'cosmetic.quote.honour.text' },
  { id: 'legendary', collection: 'quote', rarity: 'legendary', source: { kind: 'crate' }, art: 'cosmetic.quote.legendary', nameKey: 'cosmetic.quote.legendary.name', textKey: 'cosmetic.quote.legendary.text' },
  // Base flags: 15 emblem designs on the team colour; 2 starters
  { id: 'ember', collection: 'baseFlag', rarity: 'common', source: { kind: 'start' }, art: 'cosmetic.baseFlag.ember', nameKey: 'cosmetic.baseFlag.ember.name' },
  { id: 'dawn', collection: 'baseFlag', rarity: 'common', source: { kind: 'start' }, art: 'cosmetic.baseFlag.dawn', nameKey: 'cosmetic.baseFlag.dawn.name' },
  { id: 'oak', collection: 'baseFlag', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.baseFlag.oak', nameKey: 'cosmetic.baseFlag.oak.name' },
  { id: 'chevron', collection: 'baseFlag', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.baseFlag.chevron', nameKey: 'cosmetic.baseFlag.chevron.name' },
  { id: 'wave', collection: 'baseFlag', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.baseFlag.wave', nameKey: 'cosmetic.baseFlag.wave.name' },
  { id: 'mountain', collection: 'baseFlag', rarity: 'rare', source: { kind: 'capsule' }, art: 'cosmetic.baseFlag.mountain', nameKey: 'cosmetic.baseFlag.mountain.name' },
  { id: 'twin_stars', collection: 'baseFlag', rarity: 'rare', source: { kind: 'capsule' }, art: 'cosmetic.baseFlag.twin_stars', nameKey: 'cosmetic.baseFlag.twin_stars.name' },
  { id: 'mammoth', collection: 'baseFlag', rarity: 'rare', source: { kind: 'road', trophies: 350 }, art: 'cosmetic.baseFlag.mammoth', nameKey: 'cosmetic.baseFlag.mammoth.name' },
  { id: 'crossed_clubs', collection: 'baseFlag', rarity: 'rare', source: { kind: 'crate' }, art: 'cosmetic.baseFlag.crossed_clubs', nameKey: 'cosmetic.baseFlag.crossed_clubs.name' },
  { id: 'laurel', collection: 'baseFlag', rarity: 'rare', source: { kind: 'capsule' }, art: 'cosmetic.baseFlag.laurel', nameKey: 'cosmetic.baseFlag.laurel.name' },
  { id: 'cogwheel', collection: 'baseFlag', rarity: 'epic', source: { kind: 'crate' }, art: 'cosmetic.baseFlag.cogwheel', nameKey: 'cosmetic.baseFlag.cogwheel.name' },
  { id: 'lightning', collection: 'baseFlag', rarity: 'epic', source: { kind: 'capsule' }, art: 'cosmetic.baseFlag.lightning', nameKey: 'cosmetic.baseFlag.lightning.name' },
  { id: 'comet', collection: 'baseFlag', rarity: 'epic', source: { kind: 'road', trophies: 2000 }, art: 'cosmetic.baseFlag.comet', nameKey: 'cosmetic.baseFlag.comet.name' },
  { id: 'wyvern', collection: 'baseFlag', rarity: 'legendary', source: { kind: 'crate' }, art: 'cosmetic.baseFlag.wyvern', nameKey: 'cosmetic.baseFlag.wyvern.name' },
  { id: 'phoenix', collection: 'baseFlag', rarity: 'legendary', source: { kind: 'feat', feat: 'horn_of_legends' }, art: 'cosmetic.baseFlag.phoenix', nameKey: 'cosmetic.baseFlag.phoenix.name' },
  // National flags: 50 country flags in our own clean style; only ever the player's own pick
  { id: 'dk', collection: 'nationalFlag', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.dk', nameKey: 'cosmetic.nationalFlag.dk.name', country: 'dk' },
  { id: 'fo', collection: 'nationalFlag', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.fo', nameKey: 'cosmetic.nationalFlag.fo.name', country: 'fo' },
  { id: 'gl', collection: 'nationalFlag', rarity: 'rare', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.gl', nameKey: 'cosmetic.nationalFlag.gl.name', country: 'gl' },
  { id: 'se', collection: 'nationalFlag', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.se', nameKey: 'cosmetic.nationalFlag.se.name', country: 'se' },
  { id: 'no', collection: 'nationalFlag', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.no', nameKey: 'cosmetic.nationalFlag.no.name', country: 'no' },
  { id: 'fi', collection: 'nationalFlag', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.fi', nameKey: 'cosmetic.nationalFlag.fi.name', country: 'fi' },
  { id: 'is', collection: 'nationalFlag', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.is', nameKey: 'cosmetic.nationalFlag.is.name', country: 'is' },
  { id: 'gb', collection: 'nationalFlag', rarity: 'rare', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.gb', nameKey: 'cosmetic.nationalFlag.gb.name', country: 'gb' },
  { id: 'gb_eng', collection: 'nationalFlag', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.gb_eng', nameKey: 'cosmetic.nationalFlag.gb_eng.name', country: 'gb-eng' },
  { id: 'gb_sct', collection: 'nationalFlag', rarity: 'rare', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.gb_sct', nameKey: 'cosmetic.nationalFlag.gb_sct.name', country: 'gb-sct' },
  { id: 'ie', collection: 'nationalFlag', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.ie', nameKey: 'cosmetic.nationalFlag.ie.name', country: 'ie' },
  { id: 'us', collection: 'nationalFlag', rarity: 'rare', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.us', nameKey: 'cosmetic.nationalFlag.us.name', country: 'us' },
  { id: 'ca', collection: 'nationalFlag', rarity: 'rare', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.ca', nameKey: 'cosmetic.nationalFlag.ca.name', country: 'ca' },
  { id: 'de', collection: 'nationalFlag', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.de', nameKey: 'cosmetic.nationalFlag.de.name', country: 'de' },
  { id: 'fr', collection: 'nationalFlag', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.fr', nameKey: 'cosmetic.nationalFlag.fr.name', country: 'fr' },
  { id: 'nl', collection: 'nationalFlag', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.nl', nameKey: 'cosmetic.nationalFlag.nl.name', country: 'nl' },
  { id: 'be', collection: 'nationalFlag', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.be', nameKey: 'cosmetic.nationalFlag.be.name', country: 'be' },
  { id: 'lu', collection: 'nationalFlag', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.lu', nameKey: 'cosmetic.nationalFlag.lu.name', country: 'lu' },
  { id: 'ch', collection: 'nationalFlag', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.ch', nameKey: 'cosmetic.nationalFlag.ch.name', country: 'ch' },
  { id: 'at', collection: 'nationalFlag', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.at', nameKey: 'cosmetic.nationalFlag.at.name', country: 'at' },
  { id: 'it', collection: 'nationalFlag', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.it', nameKey: 'cosmetic.nationalFlag.it.name', country: 'it' },
  { id: 'es', collection: 'nationalFlag', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.es', nameKey: 'cosmetic.nationalFlag.es.name', country: 'es' },
  { id: 'pt', collection: 'nationalFlag', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.pt', nameKey: 'cosmetic.nationalFlag.pt.name', country: 'pt' },
  { id: 'pl', collection: 'nationalFlag', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.pl', nameKey: 'cosmetic.nationalFlag.pl.name', country: 'pl' },
  { id: 'cz', collection: 'nationalFlag', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.cz', nameKey: 'cosmetic.nationalFlag.cz.name', country: 'cz' },
  { id: 'hu', collection: 'nationalFlag', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.hu', nameKey: 'cosmetic.nationalFlag.hu.name', country: 'hu' },
  { id: 'gr', collection: 'nationalFlag', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.gr', nameKey: 'cosmetic.nationalFlag.gr.name', country: 'gr' },
  { id: 'ee', collection: 'nationalFlag', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.ee', nameKey: 'cosmetic.nationalFlag.ee.name', country: 'ee' },
  { id: 'lv', collection: 'nationalFlag', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.lv', nameKey: 'cosmetic.nationalFlag.lv.name', country: 'lv' },
  { id: 'lt', collection: 'nationalFlag', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.lt', nameKey: 'cosmetic.nationalFlag.lt.name', country: 'lt' },
  { id: 'ua', collection: 'nationalFlag', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.ua', nameKey: 'cosmetic.nationalFlag.ua.name', country: 'ua' },
  { id: 'ro', collection: 'nationalFlag', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.ro', nameKey: 'cosmetic.nationalFlag.ro.name', country: 'ro' },
  { id: 'bg', collection: 'nationalFlag', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.bg', nameKey: 'cosmetic.nationalFlag.bg.name', country: 'bg' },
  { id: 'tr', collection: 'nationalFlag', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.tr', nameKey: 'cosmetic.nationalFlag.tr.name', country: 'tr' },
  { id: 'jp', collection: 'nationalFlag', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.jp', nameKey: 'cosmetic.nationalFlag.jp.name', country: 'jp' },
  { id: 'kr', collection: 'nationalFlag', rarity: 'rare', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.kr', nameKey: 'cosmetic.nationalFlag.kr.name', country: 'kr' },
  { id: 'in', collection: 'nationalFlag', rarity: 'rare', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.in', nameKey: 'cosmetic.nationalFlag.in.name', country: 'in' },
  { id: 'th', collection: 'nationalFlag', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.th', nameKey: 'cosmetic.nationalFlag.th.name', country: 'th' },
  { id: 'vn', collection: 'nationalFlag', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.vn', nameKey: 'cosmetic.nationalFlag.vn.name', country: 'vn' },
  { id: 'id', collection: 'nationalFlag', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.id', nameKey: 'cosmetic.nationalFlag.id.name', country: 'id' },
  { id: 'au', collection: 'nationalFlag', rarity: 'rare', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.au', nameKey: 'cosmetic.nationalFlag.au.name', country: 'au' },
  { id: 'nz', collection: 'nationalFlag', rarity: 'rare', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.nz', nameKey: 'cosmetic.nationalFlag.nz.name', country: 'nz' },
  { id: 'br', collection: 'nationalFlag', rarity: 'rare', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.br', nameKey: 'cosmetic.nationalFlag.br.name', country: 'br' },
  { id: 'ar', collection: 'nationalFlag', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.ar', nameKey: 'cosmetic.nationalFlag.ar.name', country: 'ar' },
  { id: 'cl', collection: 'nationalFlag', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.cl', nameKey: 'cosmetic.nationalFlag.cl.name', country: 'cl' },
  { id: 'co', collection: 'nationalFlag', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.co', nameKey: 'cosmetic.nationalFlag.co.name', country: 'co' },
  { id: 'za', collection: 'nationalFlag', rarity: 'rare', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.za', nameKey: 'cosmetic.nationalFlag.za.name', country: 'za' },
  { id: 'ng', collection: 'nationalFlag', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.ng', nameKey: 'cosmetic.nationalFlag.ng.name', country: 'ng' },
  { id: 'gh', collection: 'nationalFlag', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.gh', nameKey: 'cosmetic.nationalFlag.gh.name', country: 'gh' },
  { id: 'jm', collection: 'nationalFlag', rarity: 'rare', source: { kind: 'capsule' }, art: 'cosmetic.nationalFlag.jm', nameKey: 'cosmetic.nationalFlag.jm.name', country: 'jm' },
  // Base skins: at least one per age (a restyle of that age's base; same size and mounts)
  { id: 'frost_cave', collection: 'baseSkin', rarity: 'rare', source: { kind: 'crate' }, art: 'cosmetic.baseSkin.frost_cave', nameKey: 'cosmetic.baseSkin.frost_cave.name', age: 'stone' },
  { id: 'mossy_den', collection: 'baseSkin', rarity: 'rare', source: { kind: 'road', trophies: 700 }, art: 'cosmetic.baseSkin.mossy_den', nameKey: 'cosmetic.baseSkin.mossy_den.name', age: 'stone' },
  { id: 'gilded_ziggurat', collection: 'baseSkin', rarity: 'epic', source: { kind: 'crate' }, art: 'cosmetic.baseSkin.gilded_ziggurat', nameKey: 'cosmetic.baseSkin.gilded_ziggurat.name', age: 'bronze' },
  { id: 'rose_keep', collection: 'baseSkin', rarity: 'rare', source: { kind: 'crate' }, art: 'cosmetic.baseSkin.rose_keep', nameKey: 'cosmetic.baseSkin.rose_keep.name', age: 'medieval' },
  { id: 'snowy_keep', collection: 'baseSkin', rarity: 'epic', source: { kind: 'crate' }, art: 'cosmetic.baseSkin.snowy_keep', nameKey: 'cosmetic.baseSkin.snowy_keep.name', age: 'medieval' },
  { id: 'coral_fort', collection: 'baseSkin', rarity: 'rare', source: { kind: 'crate' }, art: 'cosmetic.baseSkin.coral_fort', nameKey: 'cosmetic.baseSkin.coral_fort.name', age: 'gunpowder' },
  { id: 'copper_foundry', collection: 'baseSkin', rarity: 'rare', source: { kind: 'road', trophies: 1800 }, art: 'cosmetic.baseSkin.copper_foundry', nameKey: 'cosmetic.baseSkin.copper_foundry.name', age: 'industrial' },
  { id: 'desert_bunker', collection: 'baseSkin', rarity: 'rare', source: { kind: 'crate' }, art: 'cosmetic.baseSkin.desert_bunker', nameKey: 'cosmetic.baseSkin.desert_bunker.name', age: 'modern' },
  { id: 'midnight_neon', collection: 'baseSkin', rarity: 'epic', source: { kind: 'crate' }, art: 'cosmetic.baseSkin.midnight_neon', nameKey: 'cosmetic.baseSkin.midnight_neon.name', age: 'future' },
  { id: 'nebula_ark', collection: 'baseSkin', rarity: 'legendary', source: { kind: 'crate' }, art: 'cosmetic.baseSkin.nebula_ark', nameKey: 'cosmetic.baseSkin.nebula_ark.name', age: 'cosmic' },
  // Decorations: statues, banners, braziers, trophies and plants for the fixed base anchors; 2 starters
  { id: 'stone_idol', collection: 'decoration', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.decoration.stone_idol', nameKey: 'cosmetic.decoration.stone_idol.name', kind: 'statue' },
  { id: 'lion_statue', collection: 'decoration', rarity: 'rare', source: { kind: 'capsule' }, art: 'cosmetic.decoration.lion_statue', nameKey: 'cosmetic.decoration.lion_statue.name', kind: 'statue' },
  { id: 'knight_statue', collection: 'decoration', rarity: 'rare', source: { kind: 'crate' }, art: 'cosmetic.decoration.knight_statue', nameKey: 'cosmetic.decoration.knight_statue.name', kind: 'statue' },
  { id: 'owl_statue', collection: 'decoration', rarity: 'epic', source: { kind: 'crate' }, art: 'cosmetic.decoration.owl_statue', nameKey: 'cosmetic.decoration.owl_statue.name', kind: 'statue' },
  { id: 'astro_statue', collection: 'decoration', rarity: 'legendary', source: { kind: 'crate' }, art: 'cosmetic.decoration.astro_statue', nameKey: 'cosmetic.decoration.astro_statue.name', kind: 'statue' },
  { id: 'hide_banner', collection: 'decoration', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.decoration.hide_banner', nameKey: 'cosmetic.decoration.hide_banner.name', kind: 'banner' },
  { id: 'royal_standard', collection: 'decoration', rarity: 'rare', source: { kind: 'capsule' }, art: 'cosmetic.decoration.royal_standard', nameKey: 'cosmetic.decoration.royal_standard.name', kind: 'banner' },
  { id: 'regiment_colors', collection: 'decoration', rarity: 'rare', source: { kind: 'road', trophies: 1300 }, art: 'cosmetic.decoration.regiment_colors', nameKey: 'cosmetic.decoration.regiment_colors.name', kind: 'banner' },
  { id: 'neon_banner', collection: 'decoration', rarity: 'epic', source: { kind: 'crate' }, art: 'cosmetic.decoration.neon_banner', nameKey: 'cosmetic.decoration.neon_banner.name', kind: 'banner' },
  { id: 'fire_bowl', collection: 'decoration', rarity: 'common', source: { kind: 'start' }, art: 'cosmetic.decoration.fire_bowl', nameKey: 'cosmetic.decoration.fire_bowl.name', kind: 'brazier' },
  { id: 'iron_brazier', collection: 'decoration', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.decoration.iron_brazier', nameKey: 'cosmetic.decoration.iron_brazier.name', kind: 'brazier' },
  { id: 'gas_lamp', collection: 'decoration', rarity: 'rare', source: { kind: 'capsule' }, art: 'cosmetic.decoration.gas_lamp', nameKey: 'cosmetic.decoration.gas_lamp.name', kind: 'brazier' },
  { id: 'plasma_brazier', collection: 'decoration', rarity: 'epic', source: { kind: 'road', trophies: 2800 }, art: 'cosmetic.decoration.plasma_brazier', nameKey: 'cosmetic.decoration.plasma_brazier.name', kind: 'brazier' },
  { id: 'mammoth_tusks', collection: 'decoration', rarity: 'rare', source: { kind: 'feat', feat: 'caveman_diplomacy' }, art: 'cosmetic.decoration.mammoth_tusks', nameKey: 'cosmetic.decoration.mammoth_tusks.name', kind: 'trophy' },
  { id: 'knight_helm', collection: 'decoration', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.decoration.knight_helm', nameKey: 'cosmetic.decoration.knight_helm.name', kind: 'trophy' },
  { id: 'golden_cup', collection: 'decoration', rarity: 'epic', source: { kind: 'road', trophies: 3000 }, art: 'cosmetic.decoration.golden_cup', nameKey: 'cosmetic.decoration.golden_cup.name', kind: 'trophy' },
  { id: 'star_trophy', collection: 'decoration', rarity: 'legendary', source: { kind: 'road', trophies: 4000 }, art: 'cosmetic.decoration.star_trophy', nameKey: 'cosmetic.decoration.star_trophy.name', kind: 'trophy' },
  { id: 'shield_rack', collection: 'decoration', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.decoration.shield_rack', nameKey: 'cosmetic.decoration.shield_rack.name', kind: 'trophy' },
  { id: 'fern', collection: 'decoration', rarity: 'common', source: { kind: 'start' }, art: 'cosmetic.decoration.fern', nameKey: 'cosmetic.decoration.fern.name', kind: 'plant' },
  { id: 'olive_tree', collection: 'decoration', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.decoration.olive_tree', nameKey: 'cosmetic.decoration.olive_tree.name', kind: 'plant' },
  { id: 'topiary', collection: 'decoration', rarity: 'rare', source: { kind: 'capsule' }, art: 'cosmetic.decoration.topiary', nameKey: 'cosmetic.decoration.topiary.name', kind: 'plant' },
  { id: 'potted_cactus', collection: 'decoration', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.decoration.potted_cactus', nameKey: 'cosmetic.decoration.potted_cactus.name', kind: 'plant' },
  { id: 'bonsai', collection: 'decoration', rarity: 'rare', source: { kind: 'feat', feat: 'humble_beginnings' }, art: 'cosmetic.decoration.bonsai', nameKey: 'cosmetic.decoration.bonsai.name', kind: 'plant' },
  { id: 'crystal_flower', collection: 'decoration', rarity: 'epic', source: { kind: 'crate' }, art: 'cosmetic.decoration.crystal_flower', nameKey: 'cosmetic.decoration.crystal_flower.name', kind: 'plant' },
  // Backdrops (owner request 2026-09-30): battle background skins. Each one restyles your half's sky,
  // silhouettes, light and weather in every age (the age's own landmarks stay, so the age still reads);
  // the enemy half keeps its own look and the A11 seam blends the two. None at the start: the classic
  // sky of each age is the default.
  { id: 'golden_dusk', collection: 'backdrop', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.backdrop.golden_dusk', nameKey: 'cosmetic.backdrop.golden_dusk.name' },
  { id: 'harvest', collection: 'backdrop', rarity: 'common', source: { kind: 'capsule' }, art: 'cosmetic.backdrop.harvest', nameKey: 'cosmetic.backdrop.harvest.name' },
  { id: 'winterfall', collection: 'backdrop', rarity: 'rare', source: { kind: 'capsule' }, art: 'cosmetic.backdrop.winterfall', nameKey: 'cosmetic.backdrop.winterfall.name' },
  { id: 'blossom', collection: 'backdrop', rarity: 'rare', source: { kind: 'capsule' }, art: 'cosmetic.backdrop.blossom', nameKey: 'cosmetic.backdrop.blossom.name' },
  { id: 'starry_night', collection: 'backdrop', rarity: 'rare', source: { kind: 'crate' }, art: 'cosmetic.backdrop.starry_night', nameKey: 'cosmetic.backdrop.starry_night.name' },
  { id: 'lantern_festival', collection: 'backdrop', rarity: 'epic', source: { kind: 'capsule' }, art: 'cosmetic.backdrop.lantern_festival', nameKey: 'cosmetic.backdrop.lantern_festival.name' },
  { id: 'thunderstorm', collection: 'backdrop', rarity: 'epic', source: { kind: 'crate' }, art: 'cosmetic.backdrop.thunderstorm', nameKey: 'cosmetic.backdrop.thunderstorm.name' },
  { id: 'ember_sky', collection: 'backdrop', rarity: 'epic', source: { kind: 'road', trophies: 2100 }, art: 'cosmetic.backdrop.ember_sky', nameKey: 'cosmetic.backdrop.ember_sky.name' },
  { id: 'northern_lights', collection: 'backdrop', rarity: 'legendary', source: { kind: 'crate' }, art: 'cosmetic.backdrop.northern_lights', nameKey: 'cosmetic.backdrop.northern_lights.name' },
  { id: 'eclipse', collection: 'backdrop', rarity: 'legendary', source: { kind: 'road', trophies: 3500 }, art: 'cosmetic.backdrop.eclipse', nameKey: 'cosmetic.backdrop.eclipse.name' },
];
