"""Encodes the rendered audio for the game and writes the runtime manifest.

1. Sound effects: every variant of the sounds in one sound group is packed into one mono sprite
   sheet (`public/audio/sfx/<group>.<hash>.ogg`, Opus), with 50 ms of silence between entries.
2. Music: every cue, stinger and layer stem becomes one Ogg Opus file
   (`public/audio/music/<cue>.<hash>.ogg`): stereo for cues and stingers, mono for layer stems.
3. `src/audio/assets.gen.ts` lists the files, the sprite offsets and the loop points.

File names carry a content hash, so a browser never plays a stale cached file after an update;
files that are no longer referenced are deleted.

Usage: python build.py   (after render_music.py and render_sfx.py; see README.md)
"""
from __future__ import annotations

import hashlib
import json
import subprocess
import sys
import tempfile
from pathlib import Path

import numpy as np
import soundfile as sf

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
CACHE = HERE / ".cache"
PUBLIC = ROOT / "public" / "audio"
GEN = ROOT / "src" / "audio" / "assets.gen.ts"
SR = 48000
GAP_S = 0.05

SFX_KBPS = 40
MUSIC_KBPS = 56
MENU_KBPS = 48
STINGER_KBPS = 56
STEM_KBPS = 40


def encode(wav: Path, out_dir: Path, name: str, kbps: int, mono: bool) -> tuple[str, int]:
    out_dir.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory() as tmp:
        tmp_out = Path(tmp) / "x.ogg"
        cmd = ["ffmpeg", "-v", "error", "-y", "-i", str(wav)]
        if mono:
            cmd += ["-ac", "1"]
        cmd += ["-c:a", "libopus", "-b:a", f"{kbps}k", "-vbr", "constrained", "-compression_level", "10", "-application", "audio", "-map_metadata", "-1", "-fflags", "+bitexact", "-flags:a", "+bitexact", "-serial_offset", "1", str(tmp_out)]
        subprocess.run(cmd, check=True)
        data = tmp_out.read_bytes()
    h = hashlib.sha1(data).hexdigest()[:8]
    fname = f"{name}.{h}.ogg"
    (out_dir / fname).write_bytes(data)
    return fname, len(data)


def build_sfx(groups: list[str], sounds: dict) -> tuple[dict, dict, int]:
    idx = json.loads((CACHE / "out" / "sfx" / "index.json").read_text())
    missing = [s for s in sounds if s not in idx]
    if missing:
        raise SystemExit(f"not rendered yet: {missing}")
    sheets, entries, total = {}, {}, 0
    gap = np.zeros(int(GAP_S * SR))
    for g in groups:
        ids = [s for s in sounds if sounds[s]["group"] == g]
        if not ids:
            continue
        chunks, pos = [gap], len(gap)
        for sid in ids:
            spans = []
            for k in range(idx[sid]["variants"]):
                x, sr = sf.read(str(CACHE / "out" / "sfx" / f"{sid}.{k}.wav"), dtype="float64")
                assert sr == SR
                spans.append([round(pos / SR, 5), round(len(x) / SR, 5)])
                chunks += [x, gap]
                pos += len(x) + len(gap)
            entries[sid] = {"sheet": g, "variants": spans}
        with tempfile.TemporaryDirectory() as tmp:
            wav = Path(tmp) / f"{g}.wav"
            sf.write(str(wav), np.concatenate(chunks).astype(np.float32), SR, subtype="FLOAT")
            fname, size = encode(wav, PUBLIC / "sfx", g, SFX_KBPS, mono=True)
        sheets[g] = {"src": f"audio/sfx/{fname}", "bytes": size, "seconds": round(pos / SR, 3)}
        total += size
        print(f"  sfx/{fname}: {len(ids)} sounds, {pos / SR:.1f} s, {size / 1024:.0f} KB")
    return sheets, entries, total


def build_music() -> tuple[dict, int]:
    idx = json.loads((CACHE / "out" / "music" / "index.json").read_text())
    out, total = {}, 0
    for cue, info in sorted(idx.items()):
        stem = cue.startswith("layer.")
        kbps = STEM_KBPS if stem else STINGER_KBPS if cue.startswith("stinger.") else MENU_KBPS if cue in ("music.menu", "music.capsule") else MUSIC_KBPS
        fname, size = encode(CACHE / "out" / "music" / f"{cue}.wav", PUBLIC / "music", cue, kbps, mono=stem)
        entry = {"src": f"audio/music/{fname}", "bytes": size, "seconds": info["seconds"]}
        if "loopLength" in info:
            entry["loopStart"] = round(info["loopStart"], 6)
            entry["loopLength"] = round(info["loopLength"], 6)
        out[cue] = entry
        total += size
        print(f"  music/{fname}: {info['seconds']} s, {size / 1024:.0f} KB")
    return out, total


def prune(keep: set[str]) -> None:
    for sub in ("sfx", "music"):
        d = PUBLIC / sub
        if not d.exists():
            continue
        for f in d.iterdir():
            if f"audio/{sub}/{f.name}" not in keep:
                f.unlink()


def ts_value(v, indent: int = 0) -> str:
    return json.dumps(v, indent=None, separators=(", ", ": "))


def write_manifest(sheets: dict, entries: dict, music: dict, sfx_bytes: int, music_bytes: int) -> None:
    lines = [
        "/**",
        " * Generated by `tools/audio/build.py` from the renders in `tools/audio`. Do not edit by hand:",
        " * change the sound design or the arrangements there and rebuild (see tools/audio/README.md).",
        " *",
        " * - `SFX_SHEETS`: one Ogg Opus sprite sheet per sound group, paths relative to the site base.",
        " * - `SFX_FILES`: per sound id, its sheet and each variant's [offset, duration] in seconds.",
        " * - `MUSIC_FILES`: per music cue, stinger and layer stem, the file and, for loops, the loop",
        " *   window (`loopStart`, `loopLength` in seconds; any window of that length inside the file",
        " *   loops seamlessly).",
        " */",
        "",
        "export interface SfxSheetFile {",
        "  src: string;",
        "  bytes: number;",
        "  seconds: number;",
        "}",
        "",
        "export interface SfxFileEntry {",
        "  sheet: string;",
        "  /** [offset, duration] in seconds per variant. */",
        "  variants: readonly (readonly [number, number])[];",
        "}",
        "",
        "export interface MusicFile {",
        "  src: string;",
        "  bytes: number;",
        "  seconds: number;",
        "  loopStart?: number;",
        "  loopLength?: number;",
        "}",
        "",
        f"export const SFX_BYTES = {sfx_bytes};",
        f"export const MUSIC_BYTES = {music_bytes};",
        "",
        "export const SFX_SHEETS: Readonly<Record<string, SfxSheetFile>> = {",
    ]
    for g, s in sheets.items():
        lines.append(f"  {g}: {{ src: {json.dumps(s['src'])}, bytes: {s['bytes']}, seconds: {s['seconds']} }},")
    lines += ["};", "", "export const SFX_FILES: Readonly<Record<string, SfxFileEntry>> = {"]
    for sid, e in entries.items():
        spans = ", ".join(f"[{a}, {b}]" for a, b in e["variants"])
        lines.append(f"  {sid}: {{ sheet: {json.dumps(e['sheet'])}, variants: [{spans}] }},")
    lines += ["};", "", "export const MUSIC_FILES: Readonly<Record<string, MusicFile>> = {"]
    for cue, m in music.items():
        extra = ""
        if "loopLength" in m:
            extra = f", loopStart: {m['loopStart']}, loopLength: {m['loopLength']}"
        lines.append(f"  {json.dumps(cue)}: {{ src: {json.dumps(m['src'])}, bytes: {m['bytes']}, seconds: {m['seconds']}{extra} }},")
    lines += ["};", ""]
    GEN.write_text("\n".join(lines))


def main() -> None:
    listing = subprocess.run(["npx", "tsx", str(HERE / "list-sounds.ts")], cwd=ROOT, check=True, capture_output=True, text=True).stdout
    (CACHE / "sounds.json").write_text(listing)
    meta = json.loads(listing)
    print("sound effects:")
    sheets, entries, sfx_bytes = build_sfx(meta["groups"], meta["sounds"])
    print("music:")
    music, music_bytes = build_music()
    prune({s["src"] for s in sheets.values()} | {m["src"] for m in music.values()})
    write_manifest(sheets, entries, music, sfx_bytes, music_bytes)
    print(f"total: sfx {sfx_bytes / 1024:.0f} KB, music {music_bytes / 1024:.0f} KB -> {GEN.relative_to(ROOT)}")


if __name__ == "__main__":
    sys.exit(main())
